### ISSUE TITLE
Cannot download the zip file

### ISSUE THREAD

**Issue by dcuselton950** [AdobeDocs/experience-manager-learn.en#1]
Issue in help/getting-started-wknd-tutorial-develop/client-side-libraries.md

**Comment by godanny86** [comment]
hi @dcuselton950 thank you for raising, will update the link on the Docs side ASAP. In the interim you can use this: https://github.com/AdobeDocs/experience-manager-learn.en/blob/master/help/getting-started-wknd-tutorial-develop/assets/chapter-3/chapter3-src-code-start.zip

**Comment by godanny86** [comment]
Hi @dcuselton950 this has been corrected: https://docs.adobe.com/content/help/en/experience-manager-learn/getting-started-wknd-tutorial-develop/client-side-libraries.html#site-clientlibs 

Please let us know if you have any other issues and thanks again for raising!
