### ISSUE TITLE
Ch1: Project POM Overviews

### ISSUE THREAD

**Issue by synox** [AdobeDocs/experience-manager-learn.en#10]
When looking at chapter 1, the following table and graph have somehow a discrepancy.   

> * **ui.apps** - contains the /apps parts of the project, ie JS&CSS clientlibs, components, runmode specific configs as well as Hobbes-tests
> * **ui.content** - contains structural content and configurations (/content, /conf)

(see [project-setup.md](https://github.com/AdobeDocs/experience-manager-learn.en/blame/master/help/getting-started-wknd-tutorial-develop/project-setup.md#L255) )

But in the graph below the text, the `configs` are in ui.apps and not in `ui.content`. 

![image](https://raw.githubusercontent.com/AdobeDocs/experience-manager-learn.en/master/help/getting-started-wknd-tutorial-develop/assets/chapter-1/project-pom.png)
 
I feel like the list and the graph should somehow match.

**Comment by godanny86** [comment]
Ah, excellent point @synox ! Hopefully, this will clarify what we intended:

* **OSGi** Configs - are specific configuration files for OSGi services and are stored in **ui.apps** (this is what was meant by "configs" in the diagram)
* *Configurations* - as it refers to the **ui.content** the module was a general term meant to encompass Templates, Policies, Cloud Services, Asset Metadata schemas, etc...that is stored beneath `/conf/` in the repository

I'll revisit the diagram and text and be more clear. Thank you!

**Comment by godanny86** [comment]
This has been updated to be more clear: https://docs.adobe.com/content/help/en/experience-manager-learn/getting-started-wknd-tutorial-develop/project-setup.html
