### ISSUE TITLE
Getting "Invalid recursion selector value 'model' " error after adding a custom component and trying to add the message value.

### ISSUE THREAD

**Issue by mePriyak** [AdobeDocs/experience-manager-learn.en#100]
Issue in ./help/spa-angular-tutorial/custom-component.md
Hi,
I am using AEM 6.5 and following the tutorial https://experienceleague.adobe.com/docs/experience-manager-learn/spa-angular-tutorial. However after adding custom-component to the page on adding the value I am getting Invalid recursion selector value.

I also checked out the source code from https://github.com/adobe/aem-guides-wknd-spa.git but on deploying it to my AEM instance I am still getting the same issue.

Since I am new to AEM I am not able to resolve it.

**Comment by godanny86** [comment]
Hi @mePriyak what service pack do you have installed on 6.5?

Have you tried deploying this branch: https://github.com/adobe/aem-guides-wknd-spa/tree/Angular/custom-component-solution ?

**Comment by mePriyak** [comment]
Hi @godanny86 yes I tried deploying https://github.com/adobe/aem-guides-wknd-spa/tree/Angular/custom-component-solution and the same thing is happening for extended component. The version is AEM 6.5.0

**Comment by godanny86** [comment]
ah ok. @mePriyak is the error a javascript error or is it on the server side from AEM?

Are you able to install the latest service pack? I believe it is on 6.5.7, you can download them here: https://experience.adobe.com/#/downloads/content/software-distribution/en/aem.html

**Comment by davidjgonzalez** [comment]
@mePriyak Were you able to resolve this? If not can you re-open with the requested information? Thanks!
