### ISSUE TITLE
[AEM CS] Clarification for obtaining your region when configuring advanced networking. 

### ISSUE THREAD

**Issue by Rappa-Adobe** [AdobeDocs/experience-manager-learn.en#100]
Issue in ./help/cloud-service/networking/dedicated-egress-ip-address.md

The section that states:

First, determine the region in which the Advanced Networking is needed, by using the Cloud Manager API [listRegions](https://developer.adobe.com/experience-cloud/cloud-manager/reference/api/) operation. The region name is required to make subsequent Cloud Manager API calls. Typically, the region the Production environment resides in is used.

is a bit misleading as making that call returns several regions but not just the region that your instance is in.

**Comment by davidjgonzalez** [comment]
This API calls returns the regions you can make your advanced networking in -- usually thats whatever region your program is in, but doesnt have to be. Do you know the best way to figure out what region your program is in (and by region, i mean the region code you need to provide to the advanced networking creation API)? If such a thing exists we could add that - i just dont know off the top of my head. I know there was an ask to document what "human readable" value the region codes returned by CM map to, but not sure if that's happened yet.

**Comment by Rappa-Adobe** [comment]
I had thought you can get this from the developer console URL. I would verify this though. 

![image](https://user-images.githubusercontent.com/24437942/201439318-bcfe7b72-4cc7-4e66-a7da-ec9076b4bc2f.png)
