### ISSUE TITLE
Issue in ./help/spa-react-tutorial/custom-component.md

### ISSUE THREAD

**Issue by avitripathy01** [AdobeDocs/experience-manager-learn.en#103]
The render() in the react component should have the 'className' attribute instead of the 'class' for the 'CustomComponent' and 'CustomComponent__message' styles to display

**Comment by godanny86** [comment]
Thanks @avitripathy01 ! This has been corrected. https://experienceleague.adobe.com/docs/experience-manager-learn/spa-react-tutorial/custom-component.html?lang=en#update-the-react-component
