### ISSUE TITLE
Need to import stringUtils into the Java before this will work correctly

### ISSUE THREAD

**Issue by duselton** [AdobeDocs/experience-manager-learn.en#104]
Issue in ./help/getting-started-wknd-tutorial-develop/component-basics.md

throws a symbol error. Using standard AEM6.5.5 and the WKND project on Jan 13 2020

**Comment by godanny86** [comment]
Thanks for reporting @duselton !

**Comment by godanny86** [comment]
This has been corrected: https://experienceleague.adobe.com/docs/experience-manager-learn/getting-started-wknd-tutorial-develop/component-basics.html?lang=en#sling-models
