### ISSUE TITLE
New WKND installation not displaying CSS, fonts and images

### ISSUE THREAD

**Issue by kayest** [AdobeDocs/experience-manager-learn.en#109]
Issue in ./help/getting-started-wknd-tutorial-develop/project-setup.md

I went through all the steps here (https://experienceleague.adobe.com/docs/experience-manager-learn/getting-started-wknd-tutorial-develop/project-setup.html?lang=en#build), but once I got to this step and clicked Edit (Open the US > English page by selecting the page and clicking the Edit button in the menu bar:), the page doesn't render properly. It appears there is no CSS, fonts or images. 

The only content that appears in the header is a globe, "WKNDH Home", and search. The body contains links to Home, Facebook, Twitter and Instagram. The footer is also included... all without styling. I checked inspector and noticed this:

```
Uncaught TypeError: Cannot read property 'externalize' of undefined
    at contexthub:442
    at contexthub:446
en.html:98 Uncaught TypeError: window.injectContextHubUI is not a function
    at en.html:98
    at en.html:131
DevTools failed to load SourceMap: Could not load content for http://localhost:4502/etc.clientlibs/wknd/clientlibs/adobe-client-data-layer.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

**Comment by abetoots** [comment]
Found out using the command before the latest commit for project-setup.md which uses `-DarchetypeVersion=22` setups the correct project. I recommend reverting back to version 22 for now if you want a similar setup with the tutorial videos.

**Comment by davidjgonzalez** [comment]
Just a heads up WKND Sites tutorial has been recently updated to align to Archetype 25 - not sure if you experienced this issue before or after that update.
