### ISSUE TITLE
No content error applying page policy style

### ISSUE THREAD

**Issue by minapier** [AdobeDocs/experience-manager-learn.en#11]
Issue in help/getting-started-wknd-tutorial-develop/landing-page.md

At Step 5 of "Apply Homepage Style" near the end of Chapter 8, my home page in the tutorial gives me a "no content" error.

![add-homepage-style](https://user-images.githubusercontent.com/20262323/65159555-47beff00-da02-11e9-84be-dad745af322a.png)
![no-content](https://user-images.githubusercontent.com/20262323/65159574-4ee60d00-da02-11e9-80a1-bf514a7393bc.png)

Checking CRXDE Lite, the sling:resourceType for /wknd/en/jcr:content gets changed to cq:Page from wknd/components/structure/page. When I switch it back and save, the home page loads fine (with the page style applied).

What is causing this change, and how can it be prevented?
![homepage-sling-resource-type](https://user-images.githubusercontent.com/20262323/65159569-4c83b300-da02-11e9-9e93-f388b7cd0481.png)

Thank you.

**Comment by godanny86** [comment]
hi @minapier I have to admit I have not seen this issue before. What version of AEM are you using? Also, any service packs installed?

**Comment by minapier** [comment]
@godanny86 I'm using version 6.5.0, no service packs. Thanks!

**Comment by godanny86** [comment]
hi @minapier if you can capture the xhr post when you switch the style. Mine looks like this:

![image](https://user-images.githubusercontent.com/8974514/65345553-69012600-db8f-11e9-9bb8-dedf34eaa939.png)


![image](https://user-images.githubusercontent.com/8974514/65345474-37885a80-db8f-11e9-9c51-68babc2fddd6.png)

**Comment by minapier** [comment]
@godanny86 Here it is. I do not see ./cq:styleIds and ./sling:resourceType is cq:Page.

![xhr-post-headers](https://user-images.githubusercontent.com/20262323/65348410-1d5e7480-dbaf-11e9-99ab-616f5ba79a71.jpg)

**Comment by godanny86** [comment]
hi @minapier were you ever able to get this resolved? It almost looks like a potential permission issue. I see that the request has an authorizableId of anonymous. But I'm assuming you are logged in as admin?

**Comment by minapier** [comment]
@godanny86 It's still not resolved. You are correct: I am logged in as admin.

**Comment by godanny86** [comment]
The tutorial has been updated since this was filed. closing.
