### ISSUE TITLE
Byline component failing to deploy | Solution

### ISSUE THREAD

**Issue by lizzSoup** [AdobeDocs/experience-manager-learn.en#110]
Issue in ./help/getting-started-wknd-tutorial-develop/custom-component.md

Byline component not deploying correctly to AEM

File:
`/ui.apps/wknd/components/content/byline/.content.xml`

The `xmlns:jcr="https://` URL needs to be changed to use `http`

**Comment by godanny86** [comment]
Thanks @lizzSoup ! This has been corrected: https://experienceleague.adobe.com/docs/experience-manager-learn/getting-started-wknd-tutorial-develop/custom-component.html?lang=en#create-byline-component
