### ISSUE TITLE
Video on Service Credentials page is the same as the Intro Video

### ISSUE THREAD

**Issue by shsteimer** [AdobeDocs/experience-manager-learn.en#113]
Issue in ./help/headless-tutorial/authentication/service-credentials.md

The tutorial video on https://experienceleague.adobe.com/docs/experience-manager-learn/getting-started-with-aem-headless/authentication/service-credentials.html?lang=en#generate-service-credentials is the same as the introduction video on https://experienceleague.adobe.com/docs/experience-manager-learn/getting-started-with-aem-headless/authentication/overview.html?lang=en#authentication.

Instead it should go into details on using and managing real service credentials.

**Comment by davidjgonzalez** [comment]
Thanks @shsteimer  - a fix is waiting for deployment.

Overview videos: https://video.tv.adobe.com/v/330460/?quality=12&learn=on
Service credentials video: https://video.tv.adobe.com/v/330519/?quality=12&learn=on
