### ISSUE TITLE
Local development environment - additional guides

### ISSUE THREAD

**Issue by bartoszWesolowski** [AdobeDocs/experience-manager-learn.en#113]
Issue in ./help/foundation/development/set-up-a-local-aem-development-environment.md

Hello, 

I am reviewing the documentation around starting up local development env which is a case for every AEM project and it could be extended with some additional steps, for example:

1. How to start instance using startup scripts (double click on the jar seems ok for first encounter with AEM but it's not enough for local env setup for a real life project)
2. Cover crypto support handling (in real life projects there are some secrets that are used locally, like API keys and it would be great to have official documentation that suggest how to deal with that so all team has the same crypto key on their local environments and can reuse encrypted secrets stored in code inside OSGi configs)

**Comment by SachinMali** [comment]
@bartoszWesolowski For no-1, please see [Further options available from the Quickstart file](https://experienceleague.adobe.com/docs/experience-manager-65/deploying/deploying/custom-standalone-install.html#further-options-available-from-the-quickstart-file) also the doc has link to [Deploying and Maintaining an AEM instance](https://experienceleague.adobe.com/docs/experience-manager-65/deploying/deploying/deploy.html?lang=en).

Regarding no-2, we will see if this can be provided while keeping it very generic and brief. Meanwhile please see [Cloud Manager Environment Variables](https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/implementing/using-cloud-manager/environment-variables.html#overview)

**Comment by SachinMali** [comment]
WRT no-1, also see the newly added subsection [Using command line](https://experienceleague.adobe.com/docs/experience-manager-learn/foundation/development/set-up-a-local-aem-development-environment.html?lang=en#using-command-line)
