### ISSUE TITLE
Installation of GraphiQL on AEM 6.5.15 Does not work

### ISSUE THREAD

**Issue by adamhenderson** [AdobeDocs/experience-manager-learn.en#114]
Issue in ./help/headless-tutorial/graphql/multi-step/explore-graphql-api.md

After following the instructions and downloading and installing the package for AEM 6.5.15. Generally all documentation seems to demonstrate GraphQL/GraphiQL for AEMaaCS, 6.5.xx are not shown or made clear if compatible.

**Comment by SachinMali** [comment]
@adamhenderson There have been changes in SP15 thus it was not working, please see updated instructions at https://experienceleague.adobe.com/docs/experience-manager-learn/getting-started-with-aem-headless/how-to/install-graphiql-aem-6-5.html

Let us know if this helps and if so you can close the issue
