### ISSUE TITLE
[AEM Headless] Error Starting WKND React App

### ISSUE THREAD

**Issue by sheongperk** [AdobeDocs/experience-manager-learn.en#116]
Issue in ./help/headless-tutorial/graphql/quick-setup/local-sdk.md

I was following this AEM Headless tutorial but I’m having problems starting the WKND React App on my local Windows machine.
https://experienceleague.adobe.com/docs/experience-manager-learn/getting-started-with-aem-headless/graphql/quick-setup/local-sdk.html?lang=en
https://github.com/adobe/aem-guides-wknd-graphql

I have attached some screenshots and log files for your reference. Would you be able to help?
[Error Starting WKND React App.docx](https://github.com/AdobeDocs/experience-manager-learn.en/files/10378919/Error.Starting.WKND.React.App.docx)
[Error Starting WKND React App.docx](https://github.com/AdobeDocs/experience-manager-learn.en/files/10378929/Error.Starting.WKND.React.App.docx)

**Comment by davidjgonzalez** [comment]
@sheongperk can you try with Node 14 please, and let me know i that works? I dont believe it works on Node 18 (need to adjust the pre-reqs)
