### ISSUE TITLE
[AEM Sites] Explain how cq:dialog node is created for page properties

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/experience-manager-learn.en#117]
Issue in ./help/sites/developing/page-properties-technical-video-develop.md
The video here seems to assume that the /apps/wknd/components/page/cqDialog already exists (or may be they don't assume that it already exists, but you assume we know how to do it. On my instance it does not already exist and I'm unclear as to how to go about creating the structure in the video. Is there an easy way to do this without having to do it all manually? This video should be updated to include the creation of that directory and how to create it.

**Comment by SachinMali** [comment]
@alisonasanchez Agree, regarding the creation of dialogs, please see [Configuring your Page Properties](https://experienceleague.adobe.com/docs/experience-manager-64/developing/extending-aem/page-properties-views.html#configuring-your-page-properties).

Also to try what has been shown in the Video, the WKND sample package has been provided, see the newly added [Sample WKND page properties package](https://experienceleague.adobe.com/docs/experience-manager-learn/sites/developing/page-properties-technical-video-develop.html) section.
