### ISSUE TITLE
[AEM Sites] WKND Quick Site Creation - Explain Include Children

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/experience-manager-learn.en#118]
Issue in ./help/getting-started-wknd-tutorial-develop/site-template/author-content-publish.md
Can you be more specific about what "include children" means and what it includes and does not include? I'm not sure if it means that all subnodes will be published, or if any images/content fragments/etc. on the page will be published (or both).

**Comment by SachinMali** [comment]
@alisonasanchez I think the sentence after the 'Include children' elaborates or makes it clear. Please see highlighted line

4. Under Scope, select the WKND Site and click Include Children Settings. In the dialog, check Include children. Un-check the rest of the boxes **to ensure the entire site is published.**

**Comment by SachinMali** [comment]
@alisonasanchez  Please re-open if need more help but seems this clarifies in second sentence.
