### ISSUE TITLE
Some pages are redirecting to experienceleague landing page

### ISSUE THREAD

**Issue by mattlaun** [AdobeDocs/experience-manager-learn.en#118]
Issue in ./help/cloud-service/local-development-environment/overview.md

Earlier URLs, such at this one [1] which are still showing in Google search results, are redirecting to experienceleague landing page. The URLs appear to have changed as you can reach the correct page with a slightly different URL [2]. Note a hyphen was removed from "set-up".

[1]
https://experienceleague.adobe.com/docs/experience-manager-learn/cloud-service/local-development-environment-set-up/aem-runtime.html?lang=en#local-development-environment-set-up

[2]
https://experienceleague.adobe.com/docs/experience-manager-learn/cloud-service/local-development-environment-setup/overview.html?lang=en#local-development-environment-setup

**Comment by godanny86** [comment]
Thanks @mattlaun for reporting!

**Comment by godanny86** [comment]
Thanks again @mattlaun, very much appreciated. This has been corrected.
