### ISSUE TITLE
Screenshot referenced in this document are for AEM Cloud SDK and not AEM 6.5

### ISSUE THREAD

**Issue by s-aryal** [AdobeDocs/experience-manager-learn.en#119]
Issue in ./help/headless-tutorial/graphql/multi-step/explore-graphql-api.md

**Comment by SachinMali** [comment]
@s-aryal That's correct, those are from AEM-CS. The primary focus of the tutorial is to use AEM-CS and in the Overview section, we added a note mentioning this, please see [1]. Also for 6.5.X, please see https://experienceleague.adobe.com/docs/experience-manager-learn/getting-started-with-aem-headless/how-to/install-graphiql-aem-6-5.html

[1]
<img width="1222" alt="Screen Shot 2023-02-03 at 5 37 29 PM" src="https://user-images.githubusercontent.com/2335734/216724323-798f5def-f776-459f-954c-670ce17ac106.png">

**Comment by SachinMali** [comment]
Also as part of AEM SP-16 the GraphQL UI will be the same as AEM-CS UI..
