### ISSUE TITLE
Change file name extension

### ISSUE THREAD

**Issue by distoan1** [AdobeDocs/experience-manager-learn.en#12]
Issue in ./help/headless-tutorial/spa-editor/angular/integrate-spa.md
In the 'deploy SPA updates to AEM', step 3, please change the name of the file header.component.js to header.component.ts, to match the files from git.
[Logged by Support]

**Comment by godanny86** [comment]
Thanks @distoan1 this has been resolved.

**Comment by godanny86** [comment]
Thanks @distoan1 this has been resolved.
