### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by anneangersbach** [AdobeDocs/experience-manager-learn.en#12]
Issue in help/getting-started-wknd-tutorial-develop/style-system.md

Link to "To view an overview of Content Fragments click here." doesnt work. 
https://docs.adobe.com/content/help/en/experience-manager-learn/sites/content-fragments-feature-video-use.html
"no healthy upstream"

**Comment by godanny86** [comment]
hi @anneangersbach thank you for reporting. It should have directed you to: https://docs.adobe.com/content/help/en/experience-manager-learn/sites/content-fragments/content-fragments-feature-video-use.html

I will update the document shortly...

**Comment by godanny86** [comment]
This has been fixed: https://docs.adobe.com/content/help/en/experience-manager-learn/getting-started-wknd-tutorial-develop/style-system.html#content-fragment
