### ISSUE TITLE
mvn archetype fails to build, and fails to deploy due to old versions.

### ISSUE THREAD

**Issue by nutmix** [AdobeDocs/experience-manager-learn.en#121]
Issue in ./help/getting-started-wknd-tutorial-develop/project-setup.md

% mvn -version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /opt/apache-maven
Java version: 11.0.10, vendor: Azul Systems, Inc., runtime: /Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "11.2.2", arch: "aarch64", family: "mac"

Following the tutorial on this page: https://experienceleague.adobe.com/docs/experience-manager-learn/getting-started-wknd-tutorial-develop/project-setup.html?lang=en#advanced-maven-commands

results in 2 errors.

Firstly, on an M1 mac, it wont compile because its cant download node, you have to update the root pom.xml thus:

                    <artifactId>frontend-maven-plugin</artifactId>
                    <version>1.11.0</version>

Secondly, of you create a new project via the maven archetype, the project analyser always fails, you have to remove it from the pom in order to be able to deploy locally.

How to reproduce:

1. follow the oficial tutorial here: https://experienceleague.adobe.com/docs/experience-manager-learn/getting-started-wknd-tutorial-devel...

 

2. use the archtype to create the project:

 

 mvn -B archetype:generate \                 

    -D archetypeGroupId=com.adobe.aem \

    -D archetypeArtifactId=aem-project-archetype \

    -D archetypeVersion=25 \

    -D appTitle="WKND Sites Project" \

    -D appId="wknd" \

    -D groupId="com.adobe.aem.guides.wknd" \

    -D artifactId="aem-guides-wknd" \

    -D version="0.0.1-SNAPSHOT" \

    -D aemVersion="cloud"

 

3. Edit the pom.xml to fix the node error for M1 Macs

 

<artifactId>frontend-maven-plugin</artifactId>
<version>1.11.0</version>
 

4. try to build:

   cd aem-guides-wknd

   mvn clean install -PautoInstallSinglePackage

 

5. observe errors.  Note, I can build and deploy the wknd project from the zip file of the source, I just cant built a project from mnv archtype.

 

[INFO] - Executing Repoinit Check [repoinit]...

[INFO] - Executing Requirements Capabilities check [requirements-capabilities]...

[INFO] Analyzing feature 'com.adobe.aem.guides.wknd:aem-guides-wknd.analyse:slingosgifeature:aggregated-author.prod:0.0.1-SNAPSHOT' finished : 0 warnings, 1 errors.

[ERROR] repoinit: Parsing error in repoinit from extension : Encountered "" at line 15, column 37.

Was expecting one of:

    

[ERROR] Analyser detected errors on feature 'com.adobe.aem.guides.wknd:aem-guides-wknd.analyse:slingosgifeature:aggregated-author.prod:0.0.1-SNAPSHOT'. See log output for error messages.

[INFO] Starting analyzing feature 'com.adobe.aem.guides.wknd:aem-guides-wknd.analyse:slingosgifeature:aggregated-publish.prod:0.0.1-SNAPSHOT'...

[INFO] - Executing Api Regions analyser task that checks that listed packages are actually exported [api-regions]...

[INFO] - Executing Api Regions check order analyser task [api-regions-check-order]...

[INFO] - Executing Bundle Import/Export Check [api-regions-exportsimports]...

[INFO] - Executing Api Regions cross-feature duplicate export task [api-regions-crossfeature-dups]...

[INFO] - Executing Configuration API analyser task [configuration-api]...

[INFO] - Executing Bundle Natice Code Check [bundle-nativecode]...

[INFO] - Executing Bundle Initial Content Check [bundle-content]...

[INFO] - Executing Bundle Resources Check [bundle-resources]...

[INFO] - Executing Repoinit Check [repoinit]...

[INFO] - Executing Requirements Capabilities check [requirements-capabilities]...

[INFO] Analyzing feature 'com.adobe.aem.guides.wknd:aem-guides-wknd.analyse:slingosgifeature:aggregated-publish.prod:0.0.1-SNAPSHOT' finished : 0 warnings, 1 errors.

[ERROR] repoinit: Parsing error in repoinit from extension : Encountered "" at line 15, column 37.

Was expecting one of:

    

[ERROR] Analyser detected errors on feature 'com.adobe.aem.guides.wknd:aem-guides-wknd.analyse:slingosgifeature:aggregated-publish.prod:0.0.1-SNAPSHOT'. See log output for error messages.

[INFO] Starting analyzing feature 'com.adobe.aem.guides.wknd:aem-guides-wknd.analyse:slingosgifeature:aggregated-publish.stage:0.0.1-SNAPSHOT'...

[INFO] - Executing Api Regions analyser task that checks that listed packages are actually exported [api-regions]...

[INFO] aem-guides-wknd .................................... SUCCESS [  0.106 s]

[INFO] WKND Sites Project - Core .......................... SUCCESS [  3.056 s]

[INFO] WKND Sites Project - UI Frontend ................... SUCCESS [ 46.939 s]

[INFO] WKND Sites Project - Repository Structure Package .. SUCCESS [  0.476 s]

[INFO] WKND Sites Project - UI apps ....................... SUCCESS [  2.196 s]

[INFO] WKND Sites Project - UI content .................... SUCCESS [  1.313 s]

[INFO] WKND Sites Project - UI config ..................... SUCCESS [  0.048 s]

[INFO] WKND Sites Project - All ........................... SUCCESS [  0.145 s]

[INFO] WKND Sites Project - Integration Tests ............. SUCCESS [  4.055 s]

[INFO] WKND Sites Project - Dispatcher .................... SUCCESS [  0.029 s]

[INFO] WKND Sites Project - UI Tests ...................... SUCCESS [  0.114 s]

[INFO] WKND Sites Project - Project Analyser .............. FAILURE [ 20.309 s]

[INFO] ------------------------------------------------------------------------

[INFO] BUILD FAILURE

[INFO] ------------------------------------------------------------------------

[INFO] Total time:  01:19 min

[INFO] Finished at: 2021-03-14T17:41:07+01:00

[INFO] ------------------------------------------------------------------------

[ERROR] Failed to execute goal com.adobe.aem:aemanalyser-maven-plugin:0.0.18:analyse (default-analyse) on project aem-guides-wknd.analyse: One or more feature analyser(s) detected feature error(s), please read the plugin log for more details -> [Help 1]

[ERROR]

**Comment by godanny86** [comment]
hi @nutmix can you switch your JVM to use JDK 11 on the Software distribution portal?

https://experience.adobe.com/#/downloads/content/software-distribution/en/general.html?package=/content/software-distribution/en/details.html/content/dam/general/public/jdk-11-0-10/jdk-11.0.10_osx-x64_bin.tar.gz

**Comment by clstia** [comment]
Maven: 3.6.3
JDK: Oracle JDK 11.0.10, OpenJDK 11.0.2
Windows 10
AEM 6.5

I also encountered this error. I also tried clearing out my m2 folder before switching to Oracle JDK.

**Comment by nutmix** [comment]
The solution is to modify your pom.xml to get it to work:

<aemanalyser.version>0.9.2</aemanalyser.version>

**Comment by nutmix** [comment]
> hi @nutmix can you switch your JDK to use JDK 11 from the Software distribution portal? It looks like you are using a distribution from Azul instead of from Oracle...
> 
> https://experience.adobe.com/#/downloads/content/software-distribution/en/general.html?package=/content/software-distribution/en/details.html/content/dam/general/public/jdk-11-0-10/jdk-11.0.10_osx-x64_bin.tar.gz

Unfortunately, that link just takes me to the general experience cloud support page.

**Comment by clstia** [comment]
> The solution is to modify your pom.xml to get it to work:
> 
> <aemanalyser.version>0.9.2</aemanalyser.version>

Yup. This resolved my issue. Thanks @nutmix

**Comment by godanny86** [comment]
thanks @nutmix for reporting! This issue has been reported to in the AEM Project Archetype: https://github.com/adobe/aem-project-archetype/issues/638

Will look to update the instructions for the tutorial and a new version of the Archetype should get released soon to fix this...

**Comment by godanny86** [comment]
Archetype 26 has been released to fix the issue: https://github.com/adobe/aem-project-archetype/releases/tag/aem-project-archetype-26. Tutorial will be updated shortly.
