### ISSUE TITLE
Archetype Command

### ISSUE THREAD

**Issue by BharathValse** [AdobeDocs/experience-manager-learn.en#124]
Issue in ./help/getting-started-wknd-tutorial-develop/project-archetype/project-setup.md

The command used in the article is already 2 major versions behind. Instead of providing customers with a command they should reference the GitHub page where the most updated command is visible. This would prevent customers from using older archetype builds and always being on the latest version. https://github.com/adobe/aem-project-archetype

Label: DocBugBlitz2023

**Comment by SachinMali** [comment]
A note has been added to Create the project section.. https://experienceleague.adobe.com/docs/experience-manager-learn/getting-started-wknd-tutorial-develop/project-archetype/project-setup.html?lang=en#create
