### ISSUE TITLE
Users are not removed from AEM instance after being deleted from Admin console

### ISSUE THREAD

**Issue by rnituadobe** [AdobeDocs/experience-manager-learn.en#125]
Issue in ./help/cloud-service/accessing/overview.md

According to https://jira.corp.adobe.com/browse/GRANITE-44949, there is a known limitation which should be documented, namely if one user is deleted from Admin console, it will not be deleted from the AEM instance.
Since more customers reported this as a bug, it would be better to have it documented as working by designed.

**Label: DocBugBlitz2023**

**Comment by SachinMali** [comment]
Please see Note @ https://experienceleague.adobe.com/docs/experience-manager-learn/cloud-service/accessing/overview.html?lang=en#adobe-ims-users
