### ISSUE TITLE
Java 11 changes the debugging command

### ISSUE THREAD

**Issue by pat-lego** [AdobeDocs/experience-manager-learn.en#126]
Issue in ./help/cloud-service/debugging/aem-sdk-local-quickstart/remote-debugging.md

The debugging command in Java 11 has changed and if you use remote debugging you need to provide the following arguments 
-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005

Notice the *: in front of the 5005 port this will work in Java 11, note that this will not work in Java 8 

See it here: https://stackoverflow.com/questions/975271/remote-debugging-a-java-application

**Comment by SachinMali** [comment]
@pat-lego Thanks, it will be updated soon

**Comment by BharathValse** [comment]
@SachinMali - This bug this part of the Docbugblitz2023 initiative. Please share internal Jira when you get a chance.

**Comment by SachinMali** [comment]
@BharathValse  please see KT-13035..

**Comment by SachinMali** [comment]
This has been addressed..
