### ISSUE TITLE
Missing bundle dependency  

### ISSUE THREAD

**Issue by Pulkit-Jain-Adobe** [AdobeDocs/experience-manager-learn.en#127]
Issue in ./help/forms/adaptive-forms/service-user-tutorial-develop.md

The OSGi Bundle (Developing For User Bundle)for which the Mapping is done at ConfigMgr is not Provided in the Article. The Customer reached out to us that there Mapping is done but yet they face the issue due to Bundle un-availability on this page.

Label: DocBugBlitz2023

**Comment by girishadobe** [comment]
The bundle is available for download in the article. The following screen-shot shows you the location of the link to download the bundle in the article
![image](https://user-images.githubusercontent.com/17657584/230139341-84352b85-4fc5-4768-be4a-0bc02de7c91b.png)
