### ISSUE TITLE
[AEM Sites] "View in Admin" functionality is not mentioned

### ISSUE THREAD

**Issue by rnituadobe** [AdobeDocs/experience-manager-learn.en#129]
Issue in ./help/sites/page-authoring/page-editor-feature-video-use.md

The video on doc is missing the functionality about the "view in admin" option. So please add some details regarding the "View in Admin" OOTB behavior.

**Label: DocBugBlitz2023**

**Comment by davidjgonzalez** [comment]
Added link to documentation for information of the Page Editor, this video only covers the major features and capabilities of the Page Editor, and why you might use them. Documentation covers "every" feature.
