### ISSUE TITLE
Sling Model doesn't install

### ISSUE THREAD

**Issue by anneangersbach** [AdobeDocs/experience-manager-learn.en#13]
Issue in help/getting-started-wknd-tutorial-develop/style-system.md

I've had trouble getting the sling model into my installation. What worked in the end was using autoInstallBundle instead of autoInstallPackage.. thanks to my very helpful colleagues :-)

You might want to re-check this step. Thanks

**Comment by godanny86** [comment]
thank you @anneangersbach we will look into this and try and make it more consistent.
