### ISSUE TITLE
Compilation error and import missing in the Servlet code given in doc

### ISSUE THREAD

**Issue by sudhakaradobe** [AdobeDocs/experience-manager-learn.en#131]
Line number 39 not correct in the Servlet code attached in the document, Need the import for File class 
**code snippet:** _data_merged_document.copyToFile(new File(file_path));_

https://experienceleague.adobe.com/docs/experience-manager-learn/forms/creating-your-first-osgi-bundle/create-servlet.html?lang=en

Label: DocBugBlitz2023

**Comment by girishadobe** [comment]
Done. Made the change to the listing
