### ISSUE TITLE
Viewer Presets Not Available

### ISSUE THREAD

**Issue by suchawla1989** [AdobeDocs/experience-manager-learn.en#135]
Issue in (https://experienceleague.adobe.com/docs/experience-manager-64/assets/dynamic/troubleshoot-dms7.html?lang=en#viewers)

The viewer presets are available after we drag and drop the asset/spin sets into the Dynamic media component. 

Label: DocBugBlitz2023

**Comment by davidjgonzalez** [comment]
This issue is not an issue in 6.5
