### ISSUE TITLE
Keystore doesn't get replicated when configuring SAML 2.0

### ISSUE THREAD

**Issue by suchawla1989** [AdobeDocs/experience-manager-learn.en#136]
Issue in ./help/cloud-service/authentication/saml-2-0.md

As part of documentation https://experienceleague.adobe.com/docs/experience-manager-learn/cloud-service/authentication/saml-2-0.html?lang=en#authentication-service-keystore we have mentioned "Select authentication-service user, and select Activate from the top action bar." However the above action doesn't replicate the keystore at the publisher level. Below steps should be mentioned though until this issue is fixed
1) Create a package of the Authentication-Service user in package manager with ACL Handling mode as merge to avoid overwirting any ACL's under that path on publisher.
2) Replicate the package from Author to Publisher

This should successfully publish the keystore from Author to Publisher.

Label: DocBugBlitz2023

**Comment by davidjgonzalez** [comment]
Fixed, added instructions for how to make a package of the keystore.
