### ISSUE TITLE
AEM Log tracer plugin is not available anymore

### ISSUE THREAD

**Issue by kunwarsaluja** [AdobeDocs/experience-manager-learn.en#137]
Issue in ./help/cloud-service/debugging/aem-sdk-local-quickstart/other-tools.md

Need to update the docs as AEM log tracer plugin is not available on the CHrome store.

https://chrome.google.com/webstore/detail/aem-chrome-plug-in/ejdcnikffjleeffpigekhccpepplaode?hl=en-US = 404

**Comment by davidjgonzalez** [comment]
Thanks @kunwarsaluja  - removed the section from Docs.
