### ISSUE TITLE
Missing step to add regarding entries in js.txt and css.txt

### ISSUE THREAD

**Issue by alezzios** [AdobeDocs/experience-manager-learn.en#14]
This tutorial is missing an step in Chapter 3. This files need to be updated:

aem-guides-wknd/ui.apps/src/main/content/jcr_root/apps/wknd/clientlibs/clientlib-site/css.txt
aem-guides-wknd/ui.apps/src/main/content/jcr_root/apps/wknd/clientlibs/clientlib-site/js.txt

the css file needs these entries:

normalize.css
main.less

And the js file needs:

components/page/page.js

**Comment by godanny86** [comment]
hi @alezzios in [Implement Site Client-side Library](https://docs.adobe.com/content/help/en/experience-manager-learn/getting-started-wknd-tutorial-develop/client-side-libraries.html#site-clientlibs) steps 1-3 have you download a zip file and instruct you to overwrite clientlib-site completely. The zip should include the correctly populated css.txt file..

In [Implement Header Styles](https://docs.adobe.com/content/help/en/experience-manager-learn/getting-started-wknd-tutorial-develop/client-side-libraries.html#header-styles) Step 3 has instructions to update the js.txt file.

**Comment by godanny86** [comment]
@alezzios let me know if the above is not correct, closing for now...
