### ISSUE TITLE
Small correction as profile "autoInstallSinglePackage" is not required while preparing an all package to deploy to RDE

### ISSUE THREAD

**Issue by karanaug88** [AdobeDocs/experience-manager-learn.en#146]
Hi, 

I don't think the profile "autoInstallSinglePackage" is required while creating the artifacts to be deployed as mentioned in this document

https://experienceleague.adobe.com/docs/experience-manager-learn/cloud-service/developing/rde/how-to-use.html#prerequisite

**Comment by davidjgonzalez** [comment]
Fixed
