### ISSUE TITLE
A few errors in the Understsanding CORS page

### ISSUE THREAD

**Issue by johnb4** [AdobeDocs/experience-manager-learn.en#147]
Issue in ./help/foundation/security/understand-cross-origin-resource-sharing.md

1. Does not mention the required Dispatcher config "/clientheaders" for the request headers:
/farm
	/myfarm
		/clientheaders
			# CORS Request Headers
			"Origin"
			"Access-Control-Request-Method"
			"Access-Control-Request-Headers"
2. Includes "OPTIONS" in the example list of "supportedmethods", this is not needed. Only the headers matching the values that may be provided in "Access-Control-Request-Headers" should be listed, such as GET, HEAD, POST, etc.
3. Includes "Origin" in the list of cached response headers. ORIGIN is not a response header, so it should be removed.
4. Does not explain "Exposed Headers" well. For CORS requests (not pre-flight), if not empty these values are copied into the ACCESS_CONTROL_EXPOSE_HEADERS response header. The values in the list (header names) are then made accessible to the browser; without it, those headers are not readable by the browser.
5. In "Supported Headers" should note these are request headers.

In general, the page should discuss the two CORS request types: pre-flight requests and actual CORS requests, in addition to discussing how each OSGi configuration value is used in each request type. Also, it should discuss how the response headers are populated based on the OSGi config values and the incoming request.

Email me directly at jbunker@adobe.com if any of these comments need more clarity.

**Comment by davidjgonzalez** [comment]
Fixed - Publishing
