### ISSUE TITLE
A few errors in the Develop for CORS doc

### ISSUE THREAD

**Issue by johnb4** [AdobeDocs/experience-manager-learn.en#148]
Issue in ./help/foundation/security/develop-for-cross-origin-resource-sharing.md

1. Does not mention the required Dispatcher config "/clientheaders" for the request headers:
/farm
	/myfarm
		/clientheaders
			# CORS Request Headers
			"Origin"
			"Access-Control-Request-Method"
			"Access-Control-Request-Headers"
2. Shows the wrong directive names for caching response headers. "/myfarm /clientheaders" is wrong and should be:
/farm
	/myfarm
		/cache
			/headers

If any of this is not clear, contact me directly at jbunker@adobe.com.

**Comment by davidjgonzalez** [comment]
Fixed - publishing
