### ISSUE TITLE
[AEM Headless] Error in this tutorial doc

### ISSUE THREAD

**Issue by johnb4** [AdobeDocs/experience-manager-learn.en#149]
Issue in ./help/headless-tutorial/graphql/deployment/configurations/cors.md

Includes "OPTIONS" in the example list of "supportedmethods", this is not needed. Only the headers matching the values that may be provided in "Access-Control-Request-Headers" should be listed, such as GET, HEAD, POST, etc.

**Comment by davidjgonzalez** [comment]
Fixed - publication in progress.
