### ISSUE TITLE
"exposedheaders" is a list of response headers, not a list of request headers

### ISSUE THREAD

**Issue by johnb4** [AdobeDocs/experience-manager-learn.en#150]
Issue in ./help/foundation/security/understand-cross-origin-resource-sharing.md

The description for "Exposed Headers" (exposedheaders) is wrong:
   List of header parameters indicating request headers that browsers are allowed to access

These are not a list of request headers names but a list of response headers names that will be placed in the "ACCESS_CONTROL_EXPOSE_HEADERS" response header when a successful CORS request is made. Yes, there is no "D" in "EXPOSE" ("ACCESS_CONTROL_EXPOSE_HEADERS"). It's not used on pre-flight requests but only for CORS requests.  

Contact me at jbunker@adobe.com if you have questions about this.

**Comment by davidjgonzalez** [comment]
Fixed - publication in progress..
