### ISSUE TITLE
Document Alternatives for Sitemaps 

### ISSUE THREAD

**Issue by pat-lego** [AdobeDocs/experience-manager-learn.en#154]
The Apache Sling Sitemap Generator has support for alternative languages but it does not explain how they are found or what needs to happen to them to be located by the sitemap generator.

The code reference below [1] shows that once the page is found it needs to match many requirements for it to be included in the sitemap. 

Can we have these documented so that we can easily understand how alternative pages can be included in the sitemap.

[1] https://git.corp.adobe.com/plegault/sites-seo/blob/main/bundles/com.adobe.aem.wcm.seo.impl/src/main/java/com/adobe/aem/wcm/seo/impl/sitemap/PageTreeSitemapGeneratorImpl.java#L195-L198

**Comment by davidjgonzalez** [comment]
Hi @pat-lego, moving this question over to: https://github.com/adobe/aem-core-wcm-components/issues/2545
