### ISSUE TITLE
[AEM CS] When creating or updating a technical account the permissions required are System Administrator

### ISSUE THREAD

**Issue by kpapadopoulo** [AdobeDocs/experience-manager-learn.en#155]
Issue in ./help/headless-tutorial/authentication/service-credentials.md

When creating or updating a technical account, the permissions required are System Administrator.
The current documentation [0] states:
_

> "Ensure you are logged in as a:
> Adobe IMS Org’s Administrator
> Member of the AEM Administrators IMS Product Profile on AEM Author"

_

This is misleading, and it should be more specific. The permissions required are **System Administrator**
Please see this Slack conversation confirming this 
https://cq-dev.slack.com/archives/CR6NWG8PL/p1689174175919899?thread_ts=1682059910.658639&cid=CR6NWG8PL

[0]
https://experienceleague.adobe.com/docs/experience-manager-learn/getting-started-with-aem-headless/authentication/service-credentials.html?lang=en#create-a-technical-account

**Comment by davidjgonzalez** [comment]
Fixed - thank you!

**Comment by kpapadopoulo** [comment]
Thank you @davidjgonzalez this issue created a lot of confusion.
