### ISSUE TITLE
Text needed in addition to video

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/experience-manager-learn.en#156]
Issue in ./help/foundation/security/use-the-ssl-wizard.md
Although the video is helpful, it would be nice to have the steps written out, so that if you want to refer to them, you don't have to watch the whole video again, which is time consuming.

**Comment by davidjgonzalez** [comment]
Fixed by #157

**Comment by SachinMali** [comment]
See the updated page now with step-by-step instructions.
