### ISSUE TITLE
Step 6

### ISSUE THREAD

**Issue by raydot** [AdobeDocs/experience-manager-learn.en#16]
Issue in ./help/foundation/development/set-up-a-local-aem-development-environment.md

The link in Step 6 that reads "Add the adobe-public profile to the settings.xml file based on [the instructions here](https://repo.adobe.com/)." links to a broken link.

**Comment by godanny86** [comment]
Thanks @raydot. All of the AEM artifacts have been moved to Maven Central, so that step can be skipped. We will update the documentation and that page shortly...

**Comment by godanny86** [comment]
Fix is published. Thanks @raydot

**Comment by godanny86** [comment]
Fix is published. Thanks @raydot
