### ISSUE TITLE
Additional clarity on SDI cache configuration

### ISSUE THREAD

**Issue by jayproulx** [AdobeDocs/experience-manager-learn.en#16]
Issue in help/foundation/./development/set-up-sling-dynamic-include.md

After digging into an issue with SDI (the symptoms of which aren't super important), we found that we had a mistake in our dispatcher.any:

> Update the dispatcher.any configuration file to support (1) nocache selectors and (2) enable TTL support.

`    /glob "*.nocache.html*"`

We were missing the trailing *, which was causing the dispatcher to cache subassets for the component URN under `/path/to/cache/mypage/_jcr_content/mycomponent.html/subassets`.  In this case, mycomponent.html was created by the dispatcher as a folder, and we would see an `[an error occurred while processing this directive]` error on page in place of the desired component.

A reference to this error message and a note in the documentation would be helpful for others running into the same issue.

**Comment by jayproulx** [comment]
A note on the above, the issue was otherwise intermittent, republishing affected pages temporarily cleared that cache the the page would then work again as expected until the cache expired, but at some point after, the dispatcher would overwrite the `mycomponent.html` file with a folder with subassets again and the issue would reappear.

**Comment by godanny86** [comment]
Thanks @jayproulx the document has been updated to warn users about this misconfiguration. Thank you!
