### ISSUE TITLE
Cannot find an example of sitemapgenerator

### ISSUE THREAD

**Issue by pawee-del** [AdobeDocs/experience-manager-learn.en#161]
Since the acs commons sitemap module is now deprecated, the only option is to use wcm core sitemap functionality. We need to add more elements to the sitemap xml e.g. priority, lastmodified. However I am not able to find any example of a  java implementation of the SitemapGenerator.

**Comment by pawee-del** [comment]
sorry @Buuhuu would you be able to send me an example of a custom sitemapgenerator java implementation, we just need an example, i will try to work out the rest of the missing parts

**Comment by Buuhuu** [comment]
We will update the documentation along GA next service pack for on-prem. 

The following example shows how to implement a custom SitemapGenerator, making use of the default implementation's logic for AEM Sites. It usess the [ResourceTreeSitemapGenerator](https://javadoc.io/doc/org.apache.sling/org.apache.sling.sitemap/latest/org/apache/sling/sitemap/spi/generator/ResourceTreeSitemapGenerator.html) as a starting point to traverse a tree of pages:

```
import org.apache.sling.sitemap.spi.generator.SitemapGenerator;
import org.apache.sling.sitemap.spi.generator.ResourceTreeSitemapGenerator;
import com.adobe.aem.wcm.seo.sitemap.externalizer.SitemapLinkExternalizer;
import com.adobe.aem.wcm.seo.sitemap.PageTreeSitemapGenerator;

@Component({
  service = SitemapGenerator.class,
  property = { "service.ranking:Integer=200" }
})
public class SitemapGeneratorImpl extends ResourceTreeSitemapGenerator {

  @Reference
  private SitemapLinkExternalizer externalizer;
  @Reference 
  private PageTreeSitemapGenerator defaultGenerator;

  @Override
  protected void addResource(String name, Sitemap sitemap, Resource resource) throws SitemapException {
    Page page = resource.adaptTo(Page.class);
    if (page == null) {
      LOG.debug("Skipping resource at {}: not a page", resource.getPath());
      return;
    }
    String location = externalizer.externalize(resource);
    Url url = sitemap.addUrl(location + ".html");
    // add addotional data to the Url object like lastmod, frequency, etc.
  }

  @Override
  protected boolean shouldFollow(Resource resource) {
    // add addotional conditions to restrict which paths will be traversed
    return defaultGenerator.shouldFollow(resource);
  }

  @Override
  protected final boolean shouldInclude(Resource resource) {
    // add addotional conditions to restrict which paths will be included
    return defaultGenerator.shouldInclude(resource);
  }
}
```

**Comment by pawee-del** [comment]
thanks,

**Comment by pawee-del** [comment]
Strange, the generator class that i wrote using above as a reference isnt being triggered, @Buuhuu is there any configuration i need to set to enable?

**Comment by Buuhuu** [comment]
Hey @pawee-del I updated the example in my previous comment with a working example. It is important to set the `service.ranking` correctly (greater than 10). There are not further configurations needed.

**Comment by pawee-del** [comment]
its working now, just a quick question, if i set a page to noindex, do i have to handle it manually inside my generator class? cos i found it doesnt

**Comment by Buuhuu** [comment]
In the example above, this is what `!defaultGenerator.isNoIndex(page)` is used for.

**Comment by pawee-del** [comment]
we deploy this to aem cloud, since no access to web console, how do i turn on ondemand? do i have to check in a ondemand osgi config, test it out then revert back to scheduler? would you be able to pass me a copy of the ondemand osgi config

**Comment by Buuhuu** [comment]
This is up to your requirements. Enabling the `allOnDemand` configuration of the `SitemapGeneratorManagerImpl` helps developing on a local environment and may be useful for some really small sites or Apache Sling use cases other than AEM. 

Enabling on-demand does not _nullify_ the scheduler but the scheduler will not queue a sitemap generation job for a sitemap that is served on demand. That means if you enable the `SitemapGeneratorManagerImpl` to serve all sitemaps on demand the scheduler will run on the defined schedule but will not queue any job. 

As this does not relate to the AEM specific implementation, it would probably make sense to direct such questions to the Apache Sling Users mailing list instead.

**Comment by pawee-del** [comment]
thanks @Buuhuu  will post on the Apache Sling Users mailing list
i just wanted to use allOnDemand on the staging cloud env to test out the sitemap
