### ISSUE TITLE
DNS and AddressSpace

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/experience-manager-learn.en#161]
Issue in ./help/cloud-service/networking/vpn.md
I think that it would be helpful in this document or the [API document](https://developer.adobe.com/experience-cloud/cloud-manager/reference/api/#tag/Network-infrastructure/operation/createNetworkInfrastructure) to explicitly state that the value in the dns field should be included in the addressSpace if the dns ip is not publicly accessible, otherwise it will assume it is public. 

Also, I see in the [api document](https://developer.adobe.com/experience-cloud/cloud-manager/reference/api/#tag/Network-infrastructure/operation/createNetworkInfrastructure) that it says the addressSpace cannot be changed, I'm not sure what that means. I need instructions on how that can be changed, even if you have to delete it to change it.

**Comment by davidjgonzalez** [comment]
This nuance is better served in the actual API docs, since that really needs to be referenced to successfully setup VPN (and we dont want to re-document the API docs).

Ive moved this issue internally to docs.
