### ISSUE TITLE
Redirect Vanity URL

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/experience-manager-learn.en#165]
Issue in ./help/ams/dispatcher/disp-vanity-url.md
In the properties window where you specify the vanity URL, there is a checkbox for "Redirect Vanity URL".
This is not defined. Please define it and, if applicable, how it interacts with the dispatcher rules discussed.

**Comment by SachinMali** [comment]
Updated the **Authoring Vanity URLs** section to mention the "Redirect Vanity URL"
