### ISSUE TITLE
Link for "Setup editable templates" looks like 2 links but is actually pointing to same link

### ISSUE THREAD

**Issue by estelito-iii** [AdobeDocs/experience-manager-learn.en#167]
Under the "Recommended practices: Fast, reusable content creation model" heading, 2nd bullet point, I thought there were different links for the "Set-up" and "Editable templates" but it's actually pointing to same link.

Could probably be modified with just:
`<a href="/docs/experience-manager-learn/sites/page-authoring/template-editor-feature-video-use.html?lang=en">Set-up editable templates</a>`

instead of the current:
`<a href="/docs/experience-manager-learn/sites/page-authoring/template-editor-feature-video-use.html?lang=en">Set-up</a><a href="/docs/experience-manager-learn/sites/page-authoring/template-editor-feature-video-use.html?lang=en">e</a><a href="/docs/experience-manager-learn/sites/page-authoring/template-editor-feature-video-use.html?lang=en">ditable templates</a>`

Issue in ./help/cloud-service/introduction/drive-content-velocity-for-sites.md

**Comment by SachinMali** [comment]
Thanks and updated the links.
