### ISSUE TITLE
Not all options are listed for Bulk Upload

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/experience-manager-learn.en#169]
Issue in ./help/cloud-service/migration/bulk-import.md

In the transcript, it says only Azure and Amazon are supported. But Google also seems to be an option. This should be updated in the video and transcript. I cannot find any non-video documentation on the options available. If there is one, it should be linked.

**Comment by davidjgonzalez** [comment]
Linked to Docs for this feature, and removed mentions of what options are available as they will grow over time. Made a note that the videos do not show an exhaustive list - and for an exhaustive list refer to the product or docs.
