### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by purdueboiler1987** [AdobeDocs/experience-manager-learn.en#172]
Issue in ./help/cloud-service/introduction/architecture.md

In the More help on this feature section, the last link is broken.  

[Evolution of AEM](https://experienceleague.adobe.com/docs/experience-manager-learn/cloud-service/introduction/evolution.html?lang=en)

**Comment by davidjgonzalez** [comment]
Thanks - were working on getting this recommendation entry out of the system.
