### ISSUE TITLE
Content Fragment Link with Local SDK

### ISSUE THREAD

**Issue by scherneff** [AdobeDocs/experience-manager-learn.en#174]
Issue in ./help/headless-tutorial/graphql/multi-step/content-fragment-models.md

The tutorial requires CS based CF editor which is not available in Local SDK.  

https://experienceleague.adobe.com/docs/experience-manager-learn/getting-started-with-aem-headless/graphql/multi-step/author-content-fragments.html#create-content-fragment

This does not work for Local SDK.  This is a blocker

**Comment by davidjgonzalez** [comment]
Added a Tip to this section clarifying that if the user is on the SDK they must use the TouchUI-based UI.
