### ISSUE TITLE
Core Tenants -> Core Tenets

### ISSUE THREAD

**Issue by lucianfelix** [AdobeDocs/experience-manager-learn.en#175]
https://experienceleague.adobe.com/docs/experience-manager-learn/sites/content-fragments/understand-content-fragments-and-experience-fragments.html?lang=en#

In the comparison table, the section title it's more likely to be Core Tenets instead of Core Tenants?

Issue in ./help/sites/content-fragments/understand-content-fragments-and-experience-fragments.md

**Comment by SachinMali** [comment]
@lucianfelix you are correct, thanks, it has been fixed.
