### ISSUE TITLE
The description of the /delay time is inaccurate

### ISSUE THREAD

**Issue by johnb4** [AdobeDocs/experience-manager-learn.en#177]
Issue in ./help/ams/dispatcher/disp-vanity-url.md

This is the current description of the _/delay_ value; it is inaccurate:

> This configuration tells the Dispatcher to fetch this URL from its AEM instance it fronts every 300 seconds to fetch the list of items we want to allow through.

The _/delay_" value (in seconds) does not mean every "N" seconds. It means that Dispatcher looks at the modification time of the _/file_ (where the list of known vanity URLs are stored on the Dispatcher) and if a new incoming request for an unknown URL (such as a new vanity URL) arrives and if the delta of "(now - _/file_ modification time) < _/delay_" is true it will not refresh the _/file_. The _/file_ is refreshed only if 
1. An incoming request is not cached and does not appear in the list of vanity URLs in the file defined by _/file_.
2. At least _/delay_ seconds have elapsed since the _/file_ has been last modified (last updated). 

Why? To prevent a Denial of Service (DOS) attack by a hacker that would otherwise cause the Dispatcher to potentially make millions of requests to the Publish server using the Vanity URLs feature.

Said another way, the vanity URLs file (defined by _/file_) is only refreshed when an incoming request contains a URL that does not already appear in the vanity URLs file AND if the existing vanity URLs file is older than _/delay_ seconds (the time between when the new request is received and when the vanity URLs file was last modified).

One way to force the refresh of the _/file_ is to make a request with a URL that does not exist AND you ensure that _/delay_ seconds have elapsed since the _/file_ was last updated. An example URL would be something like "https://dispatcher-host-name.com/this-vanity-url-does-not-exist" or "https://dispatcher-host-name.com/please-hand-me-that-planet-maestro" or "https://dispatcher-host-name.com/random-vanity-url". Since these vanity URLs don't exist, it will cause the Dispatcher to refresh the _/file_, assuming _/delay_ seconds has elapsed since the _/file_ was last updated.

**Comment by davidjgonzalez** [comment]
Resolving this - thanks for the heads up
