### ISSUE TITLE
anyone try this with the latest react and node? I can't get it to compile

### ISSUE THREAD

**Issue by theboman** [AdobeDocs/experience-manager-learn.en#18]
Issue in ./help/headless-tutorial/spa-editor/react/overview.md

I am on a M1 mac :P 
using latest react / node and archtype 35

**Comment by godanny86** [comment]
Thanks @theboman. We are planning an update of this tutorial shortly to use Archetype 35. Are you using the version of React that gets generated by Archetype 35? What version of Node/npm?

**Comment by godanny86** [comment]
Thanks @theboman. We are planning an update of this tutorial shortly to use Archetype 35. Are you using the version of React that gets generated by Archetype 35? What version of Node/npm?

**Comment by theboman** [comment]
Well let me know if you would like a guinea pig for anything help with the docs etc... happy to help learn and get better

**Comment by godanny86** [comment]
That would be awesome! Always great to have a second set of eyes on this. Will let you know when we are closer to publishing. Thanks!

**Comment by davidjgonzalez** [comment]
This tutorial has been bumped to use Archetype 39 and the React/Node versions it specifies/generates.
