### ISSUE TITLE
Sample code site 1 has an extra comma 

### ISSUE THREAD

**Issue by vamkumar** [AdobeDocs/experience-manager-learn.en#181]
Issue - Access control headers line has an extra comma.
 "Access-Control-Request-Headers",
  ]

**Comment by SachinMali** [comment]
@vamkumar assuming you are referring to this page + section https://experienceleague.adobe.com/en/docs/experience-manager-learn/foundation/security/understand-cross-origin-resource-sharing#example-configurations

**Comment by vamkumar** [comment]
@SachinMali - Yes, this is the page.

**Comment by SachinMali** [comment]
This is addressed..
