### ISSUE TITLE
ValueMapValue problem with HelloWorld

### ISSUE THREAD

**Issue by NotWiggo** [AdobeDocs/experience-manager-learn.en#19]
Issue in help/getting-started-wknd-tutorial-develop/component-basics.md

This relates to the latest version of the tutorial, released a few days before Xmas 2019. Having followed the tutorial and modified HelloWorldModel.java and helloworld.html, the H1 headings do not display. A bit of messing around and it appears that the test:
data-sly-test="${hello.text}" always returns false, so the H1 is never created. hello.greeting is also null.

Not sure what I'm missing here, as this is all foreign territory to me...

**Comment by godanny86** [comment]
Hey @NotWiggo. It sounds like the bundle has not been refreshed with the updated Sling Model that includes the new methods, `getText()` and `getGreeting()`. Maybe try deploying it directly using maven:

```shell
cd aem-guides-wknd/core
mvn -PautoInstallBundle clean install
```
Also what version of AEM are you using? 6.4, 6.5, any service packs?

**Comment by NotWiggo** [comment]
AEM 6.5, no service packs (that I can think of), and it makes no difference if I use mvn...

**Comment by godanny86** [comment]
ok, thanks for the update @NotWiggo. I'll do some testing on my end as well...
