### ISSUE TITLE
Error in archetype 26 while create the project

### ISSUE THREAD

**Issue by vidhyabhushanbahl** [AdobeDocs/experience-manager-learn.en#19]
Issue in ./help/getting-started-wknd-tutorial-develop/project-archetype/project-setup.md

While following the step number 4 under create project
at https://experienceleague.adobe.com/docs/experience-manager-learn/getting-started-wknd-tutorial-develop/project-archetype/project-setup.html?lang=en

I am getting following error

_Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.2.1:generate (default-cli) on project standalone-pom: startup failed:
[ERROR] General error during conversion: Conflicting module versions. Module [groovy-all is loaded in version 2.4.16 and you are trying to load version 2.4.8_

**Comment by godanny86** [comment]
hi @vidhyabhushanbahl the tutorial was recently updated to use archetype 35. Can you try using the new commands?

```
mvn -B org.apache.maven.plugins:maven-archetype-plugin:3.2.1:generate \
    -D archetypeGroupId=com.adobe.aem \
    -D archetypeArtifactId=aem-project-archetype \
    -D archetypeVersion=35 \
    -D appTitle="WKND Sites Project" \
    -D appId="wknd" \
    -D groupId="com.adobe.aem.guides" \
    -D artifactId="aem-guides-wknd" \
    -D package="com.adobe.aem.guides.wknd" \
    -D version="0.0.1-SNAPSHOT" \
    -D aemVersion="cloud"
```

**Comment by godanny86** [comment]
closing, feel free to re-open @vidhyabhushanbahl if you still have issues.
