### ISSUE TITLE
There is a typo in the SAML 2.0 dispatcher configuration sample

### ISSUE THREAD

**Issue by ncg-it** [AdobeDocs/experience-manager-learn.en#199]
Issue in ./help/cloud-service/authentication/saml-2-0.md

The following dispatcher filter rule is invalid:
/0191 { /type "allow" /method "GET" /url "/system/sling/login" /query="*" }

A valid one would be:
/0191 { /type "allow" /method "GET" /url "/system/sling/login" /query "*" }

**Comment by davidjgonzalez** [comment]
Fixed - thanks
