### ISSUE TITLE
The guide just sucks. No idea on file structure which would be nice considering THAT IS HOW IT BUILDS!  

### ISSUE THREAD

**Issue by T-dex** [AdobeDocs/experience-manager-learn.en#2]
Issue in help/getting-started-wknd-tutorial-develop/project-setup.md

**Comment by godanny86** [comment]
I'm sorry you are frustrated @T-dex. If you have constructive thoughts on how we can improve the tutorial we would love to hear them. Unfortunately, using profanity violates Adobe's Code of Conduct and I will need to delete this post.
