### ISSUE TITLE
VPN connection only possible for environments (not Cloud Manager)

### ISSUE THREAD

**Issue by ackoch** [AdobeDocs/experience-manager-learn.en#20]
Issue in ./help/cloud-service/networking/vpn.md

The sentence 

>Virtual Private Network (VPN) allows an AEM as a Cloud Service customer to connect a Cloud Manager Program to an existing, [...]

Might give the impression, that you can connect Cloud Manager - which is not the case. The text should read

>>Virtual Private Network (VPN) allows an AEM as a Cloud Service customer to connect _ connect the environments within a Cloud Manager Program_  to an existing ....

Also it makes sense to call out explicitly that VPN on Could Manager is not supported: 

(INFO) Please note, that connecting the build environment from Cloud Manager to a VPN is _not_ supported. If you need to access binary artefacts from a private repository you need to set up a secure and password-protected repository with a URL that is available on the public internet as described here: https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/implementing/using-cloud-manager/create-application-project/setting-up-project.html?lang=en#password-protected-maven-repositories

**Comment by godanny86** [comment]
Thanks @ackoch this has been updated and published

**Comment by godanny86** [comment]
Thanks @ackoch this has been updated and published
