### ISSUE TITLE
404 Links

### ISSUE THREAD

**Issue by jtwood426** [AdobeDocs/experience-manager-learn.en#200]
Issue in ./help/assets/creative-workflows/adobe-express.md

The [Generate Image Assets Using Adobe Firefly](https://experienceleague.adobe.com/playlists/experience-manager-assets-generate-image-assets-with-adobe-firefly.html?lang=en) and 
[Create Renditions in AEM Assets](https://experienceleague.adobe.com/playlists/experience-manager-assets-create-renditions.html?lang=en) links result in a 404.

**Comment by davidjgonzalez** [comment]
This appears to have been fixed. Thanks for reporting
