### ISSUE TITLE
Problem accessing the AEM sites tutorials content

### ISSUE THREAD

**Issue by mayanksahuexp** [AdobeDocs/experience-manager-learn.en#205]
Issue in ./help/sites/experience-fragments/experience-fragments-feature-video-use.md

I have been preparing for the AEM sites content author credentials examination using the exam guide resources where I got a link for AEM tutorials, in that I got several topics to study covering MSM, personalization, page authoring, document authoring, translation, edge delivery services, experience fragments, content fragments, integrations. Now all of a sudden, the topics have disappeared from the left pane, neither there are those topics nor the subtopics of it.
Could you please help me by rectifying this issue, those material with the tutorial videos are really required for credentials exam preparation.

**Comment by davidjgonzalez** [comment]
Hi @mayanksahuexp - deepest apologies. There is an issue with the table of contents on Experience League right now. The ExL engineering team is working hard to resolve it. 

In the meantime, you should be able to access content via ExL search and filtering by Tutorials (this is the content type that Video falls under).

Again - apologize for the inconvenience.

**Comment by SachinMali** [comment]
TOC is fixed, closing it. Thanks @davidjgonzalez & @mayanksahuexp.
