### ISSUE TITLE
There are some 404 Links under the video

### ISSUE THREAD

**Issue by aaronstigberg** [AdobeDocs/experience-manager-learn.en#21]
Please look into fixing them! I clicked the "Onboarding" link and got an error.

Issue in help/assets/metadata/enhanced-smart-tags-feature-video-use.md

**Comment by godanny86** [comment]
@aaronstigberg thanks for reporting!

**Comment by godanny86** [comment]
The links on: https://docs.adobe.com/content/help/en/experience-manager-learn/assets/metadata/enhanced-smart-tags-feature-video-use.html has been updated. Let us know if there are any other issues!
