### ISSUE TITLE
nexus is down or decommissioned.

### ISSUE THREAD

**Issue by karthikreddii** [AdobeDocs/experience-manager-learn.en#22]
Issue in ./help/foundation/development/set-up-a-local-aem-development-environment.md

Nexus seems to be down. Looking for that information on internal slack found that nexus was decommissioned for AEM purposes.
Customers are facing issues in settings.xml and confirming at step7. Could you please confirm and update the documentation?

**Comment by godanny86** [comment]
Hi @karthikreddii. I believe that the you no longer need to set up the `adobe-public` profile as part of the Maven setup. Can you confirm?

**Comment by godanny86** [comment]
Thanks @karthikreddii we have updated the documentation to no longer include this unnecessary step. Thanks!

**Comment by godanny86** [comment]
Thanks @karthikreddii we have updated the documentation to no longer include this unnecessary step. Thanks!
