### ISSUE TITLE
AEM Forms + ACS Tutorial - Invalid link to "standalone java code"

### ISSUE THREAD

**Issue by nanda-dev** [AdobeDocs/experience-manager-learn.en#24]
Issue in help/forms/aem-forms-with-adobe-campaign/partone.md

In the following page, there is a link to "standalone java code", which seems to be broken/invalid:
https://docs.adobe.com/content/help/en/experience-manager-learn/forms/aem-forms-with-adobe-campaign/partone.html

This is the link to the 'standalone java code' page, that is giving a 'Requested page does not exist or you need to be logged in to see the content' error (I tried logging into my registered account, but no luck):
https://www.adobe.io/apis/experienceplatform/console/authentication/createjwt/jwt_java.html

A Java code snippet is also present in the page a little way down, but there's no mention as to whether this is the same code that is referred to by the broken link. 

Just wanted to drop a note on this. Thank you!

**Comment by godanny86** [comment]
thanks @nanda-dev for letting us know. We will get this resolved shortly..

**Comment by godanny86** [comment]
This has been resolved. Thanks @nanda-dev
