### ISSUE TITLE
Images not displayed correctly.

### ISSUE THREAD

**Issue by vidhyabhushanbahl** [AdobeDocs/experience-manager-learn.en#28]
Issue in help/sites/spa-editor/spa-editor-helloworld-tutorial-use.md

**Comment by godanny86** [comment]
Thank you @vidhyabhushanbahl for raising. This has been fixed: https://docs.adobe.com/content/help/en/experience-manager-learn/sites/spa-editor/spa-editor-helloworld-tutorial-use.html
