### ISSUE TITLE
content needs updating

### ISSUE THREAD

**Issue by pawee-del** [AdobeDocs/experience-manager-learn.en#28]
Issue in ./help/cloud-service/asset-compute/develop/project.md

it says here : 
![image](https://user-images.githubusercontent.com/72118587/158705005-4342adfc-066d-4eda-be43-c957df3e11c6.png)
its no longer valid, now its alled DX Asset Compute Work v1:
<img width="384" alt="image" src="https://user-images.githubusercontent.com/72118587/158705052-ad1fe9e1-faa7-49ed-b6d1-4df58525a5c6.png">

**Comment by davidjgonzalez** [comment]
Fixed! Thanks @pawee-del  

https://experienceleague.adobe.com/docs/experience-manager-learn/cloud-service/asset-compute/develop/project.html?lang=en
