### ISSUE TITLE
Double click jar works . Needs doc update

### ISSUE THREAD

**Issue by krishnaselvaraj** [AdobeDocs/experience-manager-learn.en#3]
I am able to open the AEM instance using the Double click option. Do we need to update the document? "You cannot start the AEM as Cloud Service Quickstart Jar by double-clicking.

"

Issue in ./help/cloud-service/local-development-environment/aem-runtime.md

**Comment by godanny86** [comment]
I think the Double Click is inconsistent at best, the surefire way is to do it via the command-line :)

**Comment by godanny86** [comment]
I think the Double Click is inconsistent at best, the surefire way is to do it via the command-line :)
