### ISSUE TITLE
Video relies on task with no fallback

### ISSUE THREAD

**Issue by austinjbennett** [AdobeDocs/experience-manager-learn.en#31]
Issue in ./help/foundation/security/use-the-ssl-wizard.md

The video walks through setting up SSL but assumes a newly set up environment with an administrative task asking to set up SSL. It does not show how to get to the SSL setup page by any other means.

**Comment by davidjgonzalez** [comment]
I'll add the following note below the video:

> Open the __SSL Configuration Wizard__ can be opened directly by navigating to __AEM Author > Tools > Security > SSL Configuration__.

Thanks
