### ISSUE TITLE
AEM as a Cloud Service - Local Dev Setup - Local Dispatcher Tools Instructions are not Windows-friendly

### ISSUE THREAD

**Issue by gotovanez** [AdobeDocs/experience-manager-learn.en#31]
Original title: The instructions on this page (https://docs.adobe.com/content/help/en/experience-manager-learn/cloud-service/local-development-environment-set-up/dispatcher-tools.html) are very confusing. It appears the person who wrote them never tried the set up but they wrote it as a second-hand account from someone else. 

Issue in help/cloud-service/./local-development-environment/dispatcher-tools.md

**Comment by davidjgonzalez** [comment]
Hi @gotovanez - Can you provide more constructive feedback? Thanks!

**Comment by gotovanez** [comment]
Hi Daniel,
I'll try to be very diplomatic here because the instructions on the help page in this email chain are not user-friendly.  Adobe needs to hire a professional technical writer to work with the engineering team to create user-friendly pages for the setting up of the developers tools.  To start with, the content needs to be divided into groups according to the operating system which developers are using on their workstations such as Windows, Linux, Ubuntu, Macs.  Each section must have content which describes the set-up of the tools for the specific operating system as verified by the technical writer, step by step.  The existing page is a mixture of unverified steps as well as videos mixing various operating systems 4requirements.  The videos do not specify whether they pertain to Linux or Windows or Mac.  If Windows is not supported, please say so at the very beginning of the Web page so developers do not waste their time.  Platinum partners are paying $25,000 in fees annually so an entry point site as this to the AEM as a Cloud Service is simply unacceptable.  So much for my diplomatic description of the problem.
On the constructive site, I followed as much as possible the "chaotic" steps in the help pages on my Windows 10 machine, where I have Docker for Windows installed.  I was able to start running the author and publish instances on it but when I tried to start the dispatcher, things went out of control completely.  Here is the screenshot of the problem.

 
  
 I tried running Docker in both Window containers mode as well as Linux container mode on my Windows 10 machine and nothing worked.  The Docker screenshot above is running in Linux containers mode.  It looks like the dispatcher scripts and configuration files have not been tested in Windows environment, which brings me back to the point I made in the first paragraph above.  If you have a solution, please let me know ASAP.

Finally, it would have been nice, if prior to releasing the AEM as a Cloud Service version of AEM, there was a beta testing program similar to the ones run for AEM 6.5 and earlier versions.  These "bugs" would have come out during that beta period and would have been fixed then, not now.  Instead, now we have set-ups which are simply not working.
I apologize for this frustrated email but I wasted almost 2 days trying to follow unclear instructions, which are OK for an open-source product but not for AEM as a commercial product.
P.S.  I set up all the tools like Homebrew, Git, Node.js, Maven on my Windows 10 machine.  I even enabled the WSL (Windows subsystem for Linux) on my Windows 10 to do so and tried the steps there as well in the Linux CLI, with no luck again.  All this effort for nothing.  Please consider valuable people's time before you release products like this in the future.

 
-----Original Message-----

**Comment by godanny86** [comment]
hi @gotovanez it looks like the screenshot of the error/issue did not get uploaded. Can you try re-uploading it? 

I'm sorry this has been frustrating for you, we will review the steps for setting up the dispatcher on Windows and make the necessary updates.

**Comment by gotovanez** [comment]
Thank You!!  Image attached.
 
 
-----Original Message-----

**Comment by godanny86** [comment]
hi @gotovanez I don't think image attachments work when replying over email. Please login to the GitHub UI to upload any screenshots or attachments.

**Comment by davidjgonzalez** [comment]
@gotovanez Thanks for the updated info! As @godanny86 mentioned we will work on validating the latest AEM SDK on Windows against the instructions and update as needed.

Understanding that the Local Dispatcher Tools is the source of most frustration - were the prior sections of the tutorial use-able for you? Or did you have issues there as well? (it sounded like you might have gotten the other tools/quickstarts installed ok, but I dont want to assume)

Sorry for the frustration, but thanks for the Git issue! Keep you posted.

**Comment by gotovanez** [comment]
As requested, attached is the screenshot from my unsuccessfully running the dispatcher script in a Windows Power Shell console with Docker Desktop and Docker for Windows installed on the computer.

![dispatcher_error_windows](https://user-images.githubusercontent.com/45862091/74187673-10ecbe00-4c1b-11ea-9821-c8fb4ae00fb7.png)

**Comment by davidjgonzalez** [comment]
@gotovanez I spent some time this weekend getting a Win 10 Pro with the latest dispatcher tools (v2.0.20, same as your screenshot) and can reproduce the same. I validated the `out` works on macOS Dispatcher Tools, and vice versa, I copied an `out` generated on macOS (and works on macOS) fails on Windows - confirming that the issue appears to be w/ the shipped docker image for windows.

I was able to briefly bend the ear the product team, and they suspect something may have broken between an earlier release version, and v2.0.20 of local dispatcher tools (but were unsure when/where without further investigation). 

I've enhanced the docs (its in the publication queue) to include Windows equivalent commands and added a note at the top stating that the local Dispatcher Tools (v2.0.20) are not currently Windows compatible.  I've also added a few items a troubleshooting section at the bottom of the page. 

The best way to be alerted when the fix to Dispatcher Tools (and/or express urgency) is released  - log a ticket with Adobe Support (and cite the internal issue # I logged, GRANITE-28964, which contains details).  

Sorry again for all the frustration and consternation.

**Comment by gotovanez** [comment]
Thank you!

**Comment by davidjgonzalez** [comment]
@gotovanezn Adobe Eng validated, and I was able to confirm, the latest DIspatcher Tools v2.0.21 work on the latest Docker (2.2.0.5 (43884)) w/ default installation toggles, for Windows 10 (Enterprise).

The latest Dispatcher Tools are available in the latest AEM SDK zip.

Would you be able to try this out at some point, and let us know if works for you?

![image](https://user-images.githubusercontent.com/1451868/79870737-6e3a8380-83b1-11ea-95ab-30e7f8bf6cb8.png)
