### ISSUE TITLE
[AEM Sites] Sitemaps - Remove incorrect information stating dependency on Core Components

### ISSUE THREAD

**Issue by clatimier** [AdobeDocs/experience-manager-learn.en#32]
Issue in ./help/sites/seo/sitemaps.md

The information "Sitemap functionality added in v2.17.6" seems incorrect
After discussing with Core components team, it looks like there is no Sitemap component included in the Core components, Sitemap is a feature based on Sling sitemap

[Logged by Support]

**Comment by davidjgonzalez** [comment]
Core Components release notes state it was released in 2.17.16 [1]. 

Im following up to understand if it was removed (which i don't think it could/should have been to support back compat of CC on 6.5.x installs). This functionality was built upon Sling Sitemaps but added CQ-specifics. Let's see what Core Comp team comes back with.


[1] https://github.com/adobe/aem-core-wcm-components/releases/tag/core.wcm.components.reactor-2.17.6
