### ISSUE TITLE
Missing step to install node modules

### ISSUE THREAD

**Issue by bstopp** [AdobeDocs/experience-manager-learn.en#34]
Issue in help/getting-started-wknd-tutorial-develop/client-side-libraries.md

On [this section](https://github.com/AdobeDocs/experience-manager-learn.en/blob/master/help/getting-started-wknd-tutorial-develop/client-side-libraries.md#use) in step 6, it says to run `npm run dev` but this generates an error.

There needs to be a command between the `cd` and `npm run` to install the modules:

```
$ cd ~/code/aem-guides-wknd/ui.frontend
$ npm install
...
added 1149 packages from 565 contributors and audited 13175 packages in 26.919s
found 0 vulnerabilities
...
$ npm run dev
...
```

**Comment by godanny86** [comment]
Thank you @bstopp !

**Comment by godanny86** [comment]
this has been fixed. Thank you!
