### ISSUE TITLE
Question on this Feature

### ISSUE THREAD

**Issue by fmarambert** [AdobeDocs/experience-manager-learn.en#34]
Issue in ./help/assets/advanced/asset-insights-launch-tutorial.md

Hi, 
i have a question and not sure where to direct. 
THis integration seems to generate s.tl() calls in Adobe Analytics for the impressions. 
I suspect that this will have an impact on the Bounce rate of a page if the Asset Impression event triggers after a page load. 

Should the Asset tracking be configured using a separate Report suite than the Report suite used for tracking the site in order to circumvent this ? 
Thanks 
Fred

**Comment by davidjgonzalez** [comment]
@fmarambert  If you do not collect, and aggregate asset impressions analytics call, then your analytics call quota will be used up much faster than normal (assuming you have multiple images per page view). Its recommended to keep the OOT implementation for this to avoid that case.
