### ISSUE TITLE
Broken Link: View the code (https://docs.adobe.com/content/help/en/experience-manager-learn/foundation/authentication/oauth-code-sample-develop.html)

### ISSUE THREAD

**Issue by sukohli** [AdobeDocs/experience-manager-learn.en#35]
Issue in help/foundation/authentication/oauth-code-sample-develop.md

The link button **View the code** is broken. It redirects the user to a 404 Page Not Found page.

[Logged by AEM Core Support]

**Comment by davidjgonzalez** [comment]
Fixed at https://docs.adobe.com/content/help/en/experience-manager-learn/foundation/authentication/oauth-code-sample-develop.html
