### ISSUE TITLE
Incorrect url

### ISSUE THREAD

**Issue by bartoszWesolowski** [AdobeDocs/experience-manager-learn.en#36]
Issue in ./help/forms/adaptive-forms/installing-aem-form-on-windows-tutorial-use.md

Link `https://helpx.adobe.com/experience-manager/6-3/forms/using/installing-configuring-aem-forms-osgi.html` from section 
```
Although we recommend following the [official documentation](https://helpx.adobe.com/experience-manager/6-3/forms/using/installing-configuring-aem-forms-osgi.html) for installing AEM Forms. The following steps can be followed to install and configure AEM Forms on Windows environment:
```

is invalid and redirects to https://experienceleague.adobe.com/docs/experience-manager-release-information/aem-release-updates/previous-updates/aem-previous-versions.html instead of actual documentation explaining what needs to be done to install Forms

**Comment by girishadobe** [comment]
I have updated the article to point to the correct URL's. Thanks for the feedback

**Comment by girishadobe** [comment]
Article updated
