### ISSUE TITLE
Writing a Custom Submit in AEM Forms - improvements

### ISSUE THREAD

**Issue by bartoszWesolowski** [AdobeDocs/experience-manager-learn.en#37]
Issue in ./help/forms/adaptive-forms/custom-submit-aem-forms-article.md

Hello, 

This article does not explain how custom submit action could be actually implemented in a real live scenario, I have some questions here:
- is the `post.POST.jsp` necessary ? could it be implemented without it (seems this is an old apporach)
- what is actually the purpose of `addfields .jsp` ? Documentation states that `This file will enable you to access the signed document.` but it's not clear how that works ?
- what is the API for the custom submit step ? Should this implement redirect to thank you page ? It would be great to extend this documentation on that matter.

**Comment by girishadobe** [comment]
Thanks for the feedback,
will update the documentation soon
