### ISSUE TITLE
[AEM Assets] Smart Tag Configuration Videos are from 6.2

### ISSUE THREAD

**Issue by ycastane** [AdobeDocs/experience-manager-learn.en#37]
Issue in help/assets/metadata/smart-tags-technical-video-setup.md

Smart Tag Configuration Videos are from 6.2 this leads to confusion as some configurations are either missing or have changed. 

[Logged by support]

**Comment by davidjgonzalez** [comment]
Fix now at: https://docs.adobe.com/content/help/en/experience-manager-learn/assets/metadata/smart-tags-technical-video-setup.html
