### ISSUE TITLE
Broken links AEM 6.x Authentication Support doc

### ISSUE THREAD

**Issue by sukohli** [AdobeDocs/experience-manager-learn.en#38]
Issue in help/foundation/authentication/authentication-support-article-understand.md

Links, such as **LDAP**, **SSO** and **Token-based (w/ encapsulated token )** are broken on the following page:
https://docs.adobe.com/content/help/en/experience-manager-learn/foundation/authentication/authentication-support-article-understand.html

[Logged by AEM Core Support]

**Comment by davidjgonzalez** [comment]
Fix is live
