### ISSUE TITLE
Storing Adaptive Form Submissions in Database

### ISSUE THREAD

**Issue by bartoszWesolowski** [AdobeDocs/experience-manager-learn.en#39]
Issue in ./help/forms/adaptive-forms/storing-adaptive-form-data-in-db.md

Hello,

This documentation does not explain much -  is it possible to make it more user friendly? Is there a github repo with the code samples - maybe it would be worth to add some code samples here with explanation? Deploying compiled bundle and CRX package does not help to understand approach.

Thanks

**Comment by girishadobe** [comment]
Thanks for the feedback
will update the article with sample code

**Comment by girishadobe** [comment]
I will need to update the article with the code using osgi annotations. I expect it to be ready by Monday/Tuesday

**Comment by davidjgonzalez** [comment]
Done
