### ISSUE TITLE
Changing when you should be inside your AEM project directory

### ISSUE THREAD

**Issue by dcuselton950** [AdobeDocs/experience-manager-learn.en#4]
Issue in help/getting-started-wknd-tutorial-develop/project-setup.md

shouldn't this instruction found in step 7 -Navigate into the aem-guides-wknd directory - really be in step 5?

**Comment by godanny86** [comment]
@dcuselton950 I'm a little confused. Are you asking about when you first generate the project from the archetype? In step 5 you are generating the project for the first time, so the directory `aem-guides-wknd` does not exist yet...

**Comment by dcuselton950** [comment]
correct, but there were not instructions to be inside the location of the directory that holds the quickstart.jar when doing the initial maven project set up. 

HTH

Very frustrated trying to get Eclipse up and running correctly and in alignment with your screencaptures.

**Comment by godanny86** [comment]
> there were not instructions to be inside the location of the directory that holds the quickstart.jar when doing the initial maven project set up.

@dcuselton950 you do not need to be in the directory where AEM quickstart.jar when doing the initial maven project set up. You can be anywhere on the file system to generate the maven project.

**Comment by dcuselton950** [comment]
thats interesting.   Might be worth mentioning. I am your Idiot test..... :-).  Have not used eclipse in about 3.5 years since I worked at Intershop where we used it a lot for over 15 years.  But Maven style is different.

**Comment by godanny86** [comment]
good feedback and sorry for the confusion. We can add more details about the file directory system and where you should run the commands.

**Comment by dcuselton950** [comment]
no worries......I was part of Magento acquisition and prepping some materials to help train up the Magento SC's on AEM.  So go thru all tutorials so get guys on a path.

**Comment by dcuselton950** [comment]
Lets close this and stay on the Eclipse Issue thread
