### ISSUE TITLE
Append Mode for multiple asset editing giving error pop up

### ISSUE THREAD

**Issue by sumanbi** [AdobeDocs/experience-manager-learn.en#4]
Hi, 

I was trying to edit multiple assets, but when i select Append Mode for multiple asset its  giving error pop up saying "Unable to edit properties."

**Comment by godanny86** [comment]
Hi @sumanbi, apologies for the delay,  I think this is more of a question for Support: https://experienceleague.adobe.com/?support-solution=Experience+Manager#support

**Comment by godanny86** [comment]
Hi @sumanbi, apologies for the delay,  I think this is more of a question for Support: https://experienceleague.adobe.com/?support-solution=Experience+Manager#support
