### ISSUE TITLE
"SampleSlingModelExporter.java" link takes to 404

### ISSUE THREAD

**Issue by vidhyabhushanbahl** [AdobeDocs/experience-manager-learn.en#40]
Issue in https://docs.adobe.com/content/help/en/experience-manager-learn/foundation/development/develop-sling-model-exporter.html

"View the Code" takes to 404.

**Comment by davidjgonzalez** [comment]
Thanks! This fix will be deployed shortly

**Comment by davidjgonzalez** [comment]
Fix is live
