### ISSUE TITLE
Missing step in Custom Component - Byline style

### ISSUE THREAD

**Issue by rubnig** [AdobeDocs/experience-manager-learn.en#42]
Issue in help/getting-started-wknd-tutorial-develop/custom-component.md

There is a step missing for getting the styling to work in the Byline component: https://docs.adobe.com/content/help/en/experience-manager-learn/getting-started-wknd-tutorial-develop/custom-component.html#add-a-default-style

The following step is missing between step 7 and step 8:

```css
@import '../components/content/byline/scss/byline.scss';
```

**Comment by rubnig** [comment]
Documentation was updated, so issue has been resolved.

**Comment by godanny86** [comment]
thank you @rubnig for raising!
