### ISSUE TITLE
Aem forms - missing information

### ISSUE THREAD

**Issue by bartoszWesolowski** [AdobeDocs/experience-manager-learn.en#44]
Issue in ./help/forms/adaptive-forms/tagging-and-saving-document-of-record-in-dam-article-use.md

Hello,

This tutorial is a bit confusing  - it does not explain how to implement this functionality - it provides a compiled bundle / already build CRX  packages which should work when installed on the AEM - in that format it's really hard to learn from this article. 

It would be great to have a documentation that explains how to implement this without a need for decompiling and reverse engineering provided packages. 

Thanks :)

**Comment by girishadobe** [comment]
sure, will list the code in the article
thanks for the feedback

**Comment by davidjgonzalez** [comment]
Fixed
