### ISSUE TITLE
WKND Sites - Page Template chapter has invalid link 

### ISSUE THREAD

**Issue by bartoszWesolowski** [AdobeDocs/experience-manager-learn.en#45]
Issue in help/getting-started-wknd-tutorial-develop/pages-templates.md

Hi, 

I am reading article on [editable templates](https://docs.adobe.com/content/help/en/experience-manager-learn/getting-started-wknd-tutorial-develop/pages-templates.html) and I found that the url in the `Create the Article Page Template` section points to 404 page: `https://docs.adobe.com/content/help/en/experience-manager-65/developing/platform/templates/page-templates-editable.htm` -> the extension is `htm` instead of `html`. 

Cheers,
Bartek

**Comment by godanny86** [comment]
thanks @bartoszWesolowski !

**Comment by godanny86** [comment]
This has been fixed. Thanks @bartoszWesolowski
