### ISSUE TITLE
tag mapping syntax error

### ISSUE THREAD

**Issue by karthikreddii** [AdobeDocs/experience-manager-learn.en#45]
Issue in ./help/assets/workfront/enhanced-connector/aem-experts-series/aem-tags-project-linked-folders-and-folder-metadata.md

Around 6 minutes 20 seconds in the video, for tag mapping, it was shown as tag/childtag but that is not working.
The right syntax is namespace:tag/childtag.
The customer reported this bug in the video

**Comment by davidjgonzalez** [comment]
Added a note below the video with correct - thanks!
