### ISSUE TITLE
Videos are way too fast

### ISSUE THREAD

**Issue by noozoo** [AdobeDocs/experience-manager-learn.en#47]
Issue in help/foundation/./cloud-manager/understand-cloud-manager-for-aem.md

I would prefer it if these videos were about half their current speed.  The talker talks so fast I have to pause often to look at the screen, and sometimes rewind to catch words that he says so quickly or slurs.  I'm a native English speaker, so I imagine it must be even harder for someone who is not.

**Comment by noozoo** [comment]
This is the page I was on
https://docs.adobe.com/content/help/en/experience-manager-learn/foundation/cloud-manager/understand-cloud-manager-for-aem.html

**Comment by godanny86** [comment]
hi @noozoo thank you for the feedback. We will keep this in mind in the future. 

Our video player was just recently upgraded to include a playback speed option: 
![image](https://user-images.githubusercontent.com/8974514/80987061-58cc4d00-8de6-11ea-983f-0433ef44083c.png)

Hope this helps!
