### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by vidhyabhushanbahl** [AdobeDocs/experience-manager-learn.en#48]
Issue in ./help/forms/adaptive-forms/tagging-and-saving-document-of-record-in-dam-article-use.md

On this page, 1 and 4 pointing to same file and there is no link to download sampleadaptiveform.zip

1. [Download the Sample Adaptive Form](https://experienceleague.adobe.com/docs/experience-manager-learn/assets/tag-and-store-in-dam-assets.zip?lang=en)

2. [Go to Forms And Documents](http://localhost:4502/aem/forms.html/content/dam/formsanddocuments)
3. Click on Create | File Upload and upload the sampleadaptiveform.zip

4. [Import the article assets](https://experienceleague.adobe.com/docs/experience-manager-learn/assets/tag-and-store-in-dam-assets.zip?lang=en) using AEM package manager

**Comment by girishadobe** [comment]
let me check and get back
thanks for reporting

**Comment by girishadobe** [comment]
I have updated the article to include the form. It will take a day or so for the changes to reflect online. In the meantime, you can download the form [from here to test the solution out](https://acrobat.adobe.com/link/track?uri=urn:aaid:scds:US:7fb69e27-77fa-4f6b-8181-9575fea109a6)

**Comment by davidjgonzalez** [comment]
Fixed
