### ISSUE TITLE
Typo in section - Read AEM Asset metadata properties

### ISSUE THREAD

**Issue by rnagaraj** [AdobeDocs/experience-manager-learn.en#49]
Issue in help/foundation/./development/understand-java-api-best-practices.md
There is a  typo in code example `Asset asset = resource.adaptTo(Page.class);`
`resource `must adapt to `Asset` not `Page`.

**Comment by godanny86** [comment]
Thanks @rnagaraj !

**Comment by godanny86** [comment]
This has been corrected. Thanks!
