### ISSUE TITLE
Adobe public releases not found

### ISSUE THREAD

**Issue by theboman** [AdobeDocs/experience-manager-learn.en#5]
Hi this is your insturctions:
https://experienceleague.adobe.com/docs/experience-manager-learn/getting-started-wknd-tutorial-develop/project-archetype/project-setup.html?lang=en

ssue in ./help/foundation/development/set-up-a-local-aem-development-environment.md

cannot navigate to this directory... 
  <properties>
                <releaseRepository-Id>adobe-public-releases</releaseRepository-Id>
                <releaseRepository-Name>Adobe Public Releases</releaseRepository-Name>
                <releaseRepository-URL>https://repo.adobe.com/nexus/content/groups/public</releaseRepository-URL>
            </properties>
            
            
         <Error>
<Code>BlobNotFound</Code>
<Message>The specified blob does not exist. RequestId:a3b74027-c01e-003f-3fe3-fdbdd6000000 Time:2021-12-31T01:15:45.1193557Z</Message>
</Error>

also here for maven repositories... 
https://mvnrepository.com/repos/adobe-public

**Comment by godanny86** [comment]
Thanks @theboman, sorry for the delay. The Adobe maven releases used to be hosted on an Adobe nexus server but have since all been moved to Maven Central. The step and reference are no longer needed and have been removed from documentation. Thanks!

**Comment by godanny86** [comment]
Thanks @theboman, sorry for the delay. The Adobe maven releases used to be hosted on an Adobe nexus server but have since all been moved to Maven Central. The step and reference are no longer needed and have been removed from documentation. Thanks!
