### ISSUE TITLE
Guide is outdated as the folder heirarchy is not the same as the screenshot in the guide. 

### ISSUE THREAD

**Issue by selango0** [AdobeDocs/experience-manager-learn.en#51]
Issue in ./help/headless-tutorial/spa-editor/react/create-project.md

`[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Child module /aem-guides-wknd-spa.react/ui.frontend of /Users/sys363/Desktop/aem-sites/aem-guides-wknd-spa.react/pom.xml does not exist @ 
[ERROR] Child module /aem-guides-wknd-spa.react/dispatcher of /Users/sys363/Desktop/aem-sites/aem-guides-wknd-spa.react/pom.xml does not exist @ `

**Comment by godanny86** [comment]
hi @selango0 what command did you use to create your project? FWIW we are working on a new version of this tutorial to use the latest version of the AEM Project Archetype (36). However I do not believe the module names have changed...

**Comment by selango0** [comment]
I'm using 

`mvn -B archetype:generate \
 -D archetypeGroupId=com.adobe.aem \
 -D archetypeArtifactId=aem-project-archetype \
 -D archetypeVersion=27 \
 -D appTitle="WKND SPA React" \
 -D appId="wknd-spa-react" \
 -D artifactId="aem-guides-wknd-spa.react" \
 -D groupId="com.adobe.aem.guides.wkndspa.react" \
 -D frontendModule="react" \
 -D aemVersion="6.5.5"
`

And this is not my folder/file structure: 
|--- aem-guides-wknd-spa.react/
 

>    |--- all/
>     |--- analyse/
>     |--- core/
>     |--- ui.apps/
>     |--- ui.apps.structure/
>     |--- ui.config/
>     |--- ui.content/
>     |--- ui.frontend/
>     |--- ui.tests /
>     |--- it.tests/
>     |--- dispatcher/
>     |--- analyse/
>     |--- pom.xml
>     |--- README.md
>     |--- .gitignore

**Comment by godanny86** [comment]
Ah with 6.5.5 I don't think the `analyse` module gets created. Is that the only difference?

**Comment by selango0** [comment]
> 

I also don't have the ui.frontend/ folder, but rather specific versions of it: 
![Screen Shot 2022-06-03 at 12 14 00 PM](https://user-images.githubusercontent.com/20031829/171904667-b1716361-eff1-417b-bc0c-69334618f431.png)



Which is why I get the errors above

**Comment by godanny86** [comment]
Yes that structure does not look correct. Are you sure you used this command:

```
mvn -B archetype:generate \
 -D archetypeGroupId=com.adobe.aem \
 -D archetypeArtifactId=aem-project-archetype \
 -D archetypeVersion=27 \
 -D appTitle="WKND SPA React" \
 -D appId="wknd-spa-react" \
 -D artifactId="aem-guides-wknd-spa.react" \
 -D groupId="com.adobe.aem.guides.wkndspa.react" \
 -D frontendModule="react" \
 -D aemVersion="6.5.5"
 ```
 
What version of Maven are you using? Did the project get generated successfully? You should see the following message after generating the project:

```
Creating content skeleton...
[INFO] Project created from Archetype in dir: /Users/Desktop/aem-guides-wknd-spa.react
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for aem-guides-wknd-spa.react 1.0.0-SNAPSHOT:
[INFO]
[INFO] aem-guides-wknd-spa.react .......................... SUCCESS [  8.388 s]
[INFO] WKND SPA React - Core .............................. SKIPPED
[INFO] WKND SPA React - UI Frontend ....................... SKIPPED
[INFO] WKND SPA React - Repository Structure Package ...... SKIPPED
[INFO] WKND SPA React - UI apps ........................... SKIPPED
[INFO] WKND SPA React - UI content ........................ SKIPPED
[INFO] WKND SPA React - UI config ......................... SKIPPED
[INFO] WKND SPA React - All ............................... SKIPPED
[INFO] WKND SPA React - Integration Tests ................. SKIPPED
[INFO] WKND SPA React - Dispatcher ........................ SKIPPED
[INFO] WKND SPA React - UI Tests .......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10.087 s
[INFO] Finished at: 2022-06-03T09:16:50-07:00
[INFO] ------------------------------------------------------------------------
```

**Comment by selango0** [comment]
> > 
Maven version: `Apache Maven 3.8.4 `

I just removed my entire folder and ran the command again. Same issue. This is the full message:

> [INFO] ------------------< org.apache.maven:standalone-pom >-------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] >>> maven-archetype-plugin:3.2.1:generate (default-cli) > generate-sources @ standalone-pom >>>
[INFO] 
[INFO] <<< maven-archetype-plugin:3.2.1:generate (default-cli) < generate-sources @ standalone-pom <<<
[INFO] 
[INFO] 
[INFO] --- maven-archetype-plugin:3.2.1:generate (default-cli) @ standalone-pom ---
[INFO] Generating project in Batch mode
[INFO] Archetype repository not defined. Using the one from [com.adobe.aem:aem-project-archetype:36] found in catalog remote
[INFO] ----------------------------------------------------------------------------
[INFO] Using following parameters for creating project from Archetype: aem-project-archetype:27
[INFO] ----------------------------------------------------------------------------
[INFO] Parameter: groupId, Value: com.adobe.aem.guides.wkndspa.react
[INFO] Parameter: artifactId, Value: aem-guides-wknd-spa.react
[INFO] Parameter: version, Value: 1.0.0-SNAPSHOT
[INFO] Parameter: package, Value: com.adobe.aem.guides.wkndspa.react
[INFO] Parameter: packageInPathFormat, Value: com/adobe/aem/guides/wkndspa/react
[INFO] Parameter: frontendModule, Value: react
[INFO] Parameter: artifactId, Value: aem-guides-wknd-spa.react
[INFO] Parameter: sdkFormsVersion, Value: latest
[INFO] Parameter: package, Value: com.adobe.aem.guides.wkndspa.react
[INFO] Parameter: appId, Value: wknd-spa-react
[INFO] Parameter: version, Value: 1.0.0-SNAPSHOT
[INFO] Parameter: appTitle, Value: WKND SPA React
[INFO] Parameter: includeErrorHandler, Value: n
[INFO] Parameter: singleCountry, Value: y
[INFO] Parameter: amp, Value: n
[INFO] Parameter: datalayer, Value: y
[INFO] Parameter: includeForms, Value: n
[INFO] Parameter: groupId, Value: com.adobe.aem.guides.wkndspa.react
[INFO] Parameter: aemVersion, Value: 6.5.5
[INFO] Parameter: language, Value: en
[INFO] Parameter: country, Value: us
[INFO] Parameter: includeDispatcherConfig, Value: y
[INFO] Parameter: commerceEndpoint, Value: https://hostsample.com/graphql
[INFO] Parameter: sdkVersion, Value: latest
[INFO] Parameter: includeCommerce, Value: n
[INFO] Parameter: enableDynamicMedia, Value: n
[INFO] Parameter: includeExamples, Value: n
[INFO] Parent element not overwritten in /Users/sample/Desktop/aem-sites/aem-guides-wknd-spa.react/all/pom.xml
[INFO] Parent element not overwritten in /Users/sample/Desktop/aem-sites/aem-guides-wknd-spa.react/analyse/pom.xml
[INFO] Parent element not overwritten in /Users/sample/Desktop/aem-sites/aem-guides-wknd-spa.react/core/pom.xml
[INFO] Parent element not overwritten in /Users/sample/Desktop/aem-sites/aem-guides-wknd-spa.react/dispatcher.ams/pom.xml
[INFO] Parent element not overwritten in /Users/sample/Desktop/aem-sites/aem-guides-wknd-spa.react/dispatcher.cloud/pom.xml
[INFO] Parent element not overwritten in /Users/sample/Desktop/aem-sites/aem-guides-wknd-spa.react/ui.frontend.general/pom.xml
[WARNING] Don't override file /Users/sample/Desktop/aem-sites/aem-guides-wknd-spa.react/ui.frontend.general/pom.xml
[INFO] Parent element not overwritten in /Users/sample/Desktop/aem-sites/aem-guides-wknd-spa.react/ui.frontend.angular/pom.xml
[WARNING] Don't override file /Users/sample/Desktop/aem-sites/aem-guides-wknd-spa.react/ui.frontend.angular/pom.xml
[INFO] Parent element not overwritten in /Users/sample/Desktop/aem-sites/aem-guides-wknd-spa.react/ui.frontend.react/pom.xml
[WARNING] Don't override file /Users/sample/Desktop/aem-sites/aem-guides-wknd-spa.react/ui.frontend.react/pom.xml
[INFO] Parent element not overwritten in /Users/sample/Desktop/aem-sites/aem-guides-wknd-spa.react/ui.apps/pom.xml
[INFO] Parent element not overwritten in /Users/sample/Desktop/aem-sites/aem-guides-wknd-spa.react/ui.config/pom.xml
[INFO] Parent element not overwritten in /Users/sample/Desktop/aem-sites/aem-guides-wknd-spa.react/ui.content/pom.xml
[WARNING] CP Don't override file /Users/sample/Desktop/aem-sites/aem-guides-wknd-spa.react/ui.content/src/main/content/jcr_root/content/wknd-spa-react/_jcr_content/image/file
[INFO] Parent element not overwritten in /Users/sample/Desktop/aem-sites/aem-guides-wknd-spa.react/it.tests/pom.xml
[INFO] Parent element not overwritten in /Users/sample/Desktop/aem-sites/aem-guides-wknd-spa.react/ui.tests/pom.xml
[WARNING] Don't override file /Users/sample/Desktop/aem-sites/aem-guides-wknd-spa.react/ui.tests/pom.xml
[WARNING] CP Don't override file /Users/sample/Desktop/aem-sites/aem-guides-wknd-spa.react/ui.tests/test-module/README.md
[WARNING] CP Don't override file /Users/sample/Desktop/aem-sites/aem-guides-wknd-spa.react/ui.tests/test-module/wdio.conf.local.js
[WARNING] CP Don't override file /Users/sample/Desktop/aem-sites/aem-guides-wknd-spa.react/ui.tests/test-module/wdio.conf.cloud.js
[WARNING] CP Don't override file /Users/sample/Desktop/aem-sites/aem-guides-wknd-spa.react/ui.tests/test-module/assets/image.png
[WARNING] CP Don't override file /Users/sample/Desktop/aem-sites/aem-guides-wknd-spa.react/ui.tests/test-module/wdio.conf.commons.js
[WARNING] CP Don't override file /Users/sample/Desktop/aem-sites/aem-guides-wknd-spa.react/ui.tests/test-module/lib/wdio.commands.js
[WARNING] CP Don't override file /Users/sample/Desktop/aem-sites/aem-guides-wknd-spa.react/ui.tests/test-module/lib/config.js
[WARNING] CP Don't override file /Users/sample/Desktop/aem-sites/aem-guides-wknd-spa.react/ui.tests/test-module/lib/commons.js
[WARNING] CP Don't override file /Users/sample/Desktop/aem-sites/aem-guides-wknd-spa.react/ui.tests/test-module/package.json
[WARNING] CP Don't override file /Users/sample/Desktop/aem-sites/aem-guides-wknd-spa.react/ui.tests/test-module/.eslintrc.js
[WARNING] CP Don't override file /Users/sample/Desktop/aem-sites/aem-guides-wknd-spa.react/ui.tests/test-module/specs/aem/basic.js
[WARNING] CP Don't override file /Users/sample/Desktop/aem-sites/aem-guides-wknd-spa.react/ui.tests/test-module/specs/aem/login.js
[WARNING] CP Don't override file /Users/sample/Desktop/aem-sites/aem-guides-wknd-spa.react/ui.tests/test-module/specs/aem/sites.js
[WARNING] CP Don't override file /Users/sample/Desktop/aem-sites/aem-guides-wknd-spa.react/ui.tests/test-module/specs/aem/assets.js
[INFO] Parent element not overwritten in /Users/sample/Desktop/aem-sites/aem-guides-wknd-spa.react/ui.apps.structure/pom.xml
[INFO] Executing META-INF/archetype-post-generate.groovy post-generation script
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.774 s
[INFO] Finished at: 2022-06-03T12:22:29-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.2.1:generate (default-cli) on project standalone-pom: startup failed:
[ERROR] General error during conversion: Conflicting module versions. Module [groovy-all is loaded in version 2.4.16 and you are trying to load version 2.4.8
[ERROR] 
[ERROR] groovy.lang.GroovyRuntimeException: Conflicting module versions. Module [groovy-all is loaded in version 2.4.16 and you are trying to load version 2.4.8
[ERROR] 	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl$DefaultModuleListener.onModule(MetaClassRegistryImpl.java:529)
[ERROR] 	at org.codehaus.groovy.runtime.m12n.ExtensionModuleScanner.scanExtensionModuleFromProperties(ExtensionModuleScanner.java:81)
[ERROR] 	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.registerExtensionModuleFromProperties(MetaClassRegistryImpl.java:174)
[ERROR] 	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl$registerExtensionModuleFromProperties.call(Unknown Source)
[ERROR] 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
[ERROR] 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
[ERROR] 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:144)
[ERROR] 	at groovy.grape.GrapeIvy.processCategoryMethods(GrapeIvy.groovy:290)
[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR] 	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
[ERROR] 	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
[ERROR] 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
[ERROR] 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:157)
[ERROR] 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:177)
[ERROR] 	at groovy.grape.GrapeIvy.grab(GrapeIvy.groovy:261)
[ERROR] 	at groovy.grape.Grape.grab(Grape.java:167)
[ERROR] 	at groovy.grape.GrabAnnotationTransformation.visit(GrabAnnotationTransformation.java:376)
[ERROR] 	at org.codehaus.groovy.transform.ASTTransformationVisitor$3.call(ASTTransformationVisitor.java:346)
[ERROR] 	at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:966)
[ERROR] 	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:626)
[ERROR] 	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:602)
[ERROR] 	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:579)
[ERROR] 	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:323)
[ERROR] 	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:293)
[ERROR] 	at groovy.lang.GroovyShell.parseClass(GroovyShell.java:677)
[ERROR] 	at groovy.lang.GroovyShell.parse(GroovyShell.java:689)
[ERROR] 	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:573)
[ERROR] 	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:612)
[ERROR] 	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:583)
[ERROR] 	at org.apache.maven.archetype.generator.DefaultFilesetArchetypeGenerator.generateArchetype(DefaultFilesetArchetypeGenerator.java:234)
[ERROR] 	at org.apache.maven.archetype.generator.DefaultArchetypeGenerator.processFileSetArchetype(DefaultArchetypeGenerator.java:133)
[ERROR] 	at org.apache.maven.archetype.generator.DefaultArchetypeGenerator.generateArchetype(DefaultArchetypeGenerator.java:104)
[ERROR] 	at org.apache.maven.archetype.generator.DefaultArchetypeGenerator.generateArchetype(DefaultArchetypeGenerator.java:148)
[ERROR] 	at org.apache.maven.archetype.generator.DefaultArchetypeGenerator.generateArchetype(DefaultArchetypeGenerator.java:163)
[ERROR] 	at org.apache.maven.archetype.DefaultArchetypeManager.generateProjectFromArchetype(DefaultArchetypeManager.java:75)
[ERROR] 	at org.apache.maven.archetype.mojos.CreateProjectFromArchetypeMojo.execute(CreateProjectFromArchetypeMojo.java:211)
[ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:972)
[ERROR] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
[ERROR] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[ERROR] 
[ERROR] 1 error
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by godanny86** [comment]
Can you try this command w/ latest archetype?

```
mvn -B org.apache.maven.plugins:maven-archetype-plugin:3.2.1:generate \
 -D archetypeGroupId=com.adobe.aem \
 -D archetypeArtifactId=aem-project-archetype \
 -D archetypeVersion=36\
 -D appTitle="WKND SPA React" \
 -D appId="wknd-spa-react" \
 -D artifactId="aem-guides-wknd-spa.react" \
 -D groupId="com.adobe.aem.guides.wkndspa.react" \
 -D frontendModule="react" \
 -D aemVersion="6.5.5"
 ```

**Comment by selango0** [comment]
> Can you try this command w/ latest archetype?
> 
> ```
> mvn -B org.apache.maven.plugins:maven-archetype-plugin:3.2.1:generate \
>  -D archetypeGroupId=com.adobe.aem \
>  -D archetypeArtifactId=aem-project-archetype \
>  -D archetypeVersion=36\
>  -D appTitle="WKND SPA React" \
>  -D appId="wknd-spa-react" \
>  -D artifactId="aem-guides-wknd-spa.react" \
>  -D groupId="com.adobe.aem.guides.wkndspa.react" \
>  -D frontendModule="react" \
>  -D aemVersion="6.5.5"
> ```

This worked! Getting build success message now.

**Comment by godanny86** [comment]
nice! you should probably be able to complete most of the tutorial, might be some slight differences with the new archetype

**Comment by selango0** [comment]
> 

Thanks!
