### ISSUE TITLE
Possibly incomplete content on the page...

### ISSUE THREAD

**Issue by actinium15** [AdobeDocs/experience-manager-learn.en#52]
Issue in help/foundation/authentication/oauth-code-sample-develop.md

The page says: "The diagram below illustrates the request flow in the context of AEM."

However, the page has no diagram.
Also, the page appears quite sparse for the topic it aims to handle - maybe the content was accidentally removed, or was relocated to another page without any outgoing link for that here. Please review.

**Comment by davidjgonzalez** [comment]
Thanks @actinium15 - added the image back; this fix is pending deployment to adobe docs servers

**Comment by davidjgonzalez** [comment]
This fix is on docs.adobe.com now
