### ISSUE TITLE
Link to JCR 2.0 Javadoc is broken

### ISSUE THREAD

**Issue by kwin** [AdobeDocs/experience-manager-learn.en#53]
Issue in ./help/foundation/development/understand-java-api-best-practices.md

The link in https://experienceleague.adobe.com/docs/experience-manager-learn/foundation/development/understand-java-api-best-practices.html?lang=en#jcr-apis pointing to https://www.adobe.io/experience-manager/reference-materials/spec/javax.jcr/javadocs/jcr-2.0/index.html returns a 404

**Comment by kwin** [comment]
Was a temporary glitch. The JCR javadoc and spec links work again.

**Comment by davidjgonzalez** [comment]
I've updated them to point to the new domain anyhow (might as well skip the Redirect) .. should be published this week
