### ISSUE TITLE
[AEM Forms] The link to download the jar file doesn't work

### ISSUE THREAD

**Issue by masumalli** [AdobeDocs/experience-manager-learn.en#54]
Issue in help/forms/handling-form-submissions/invoking-aem-workflow-on-form-submission-article-use.md

The link to the following doesn't work.
https://forms.enablementadobe.com/content/DemoServerBundles/SetValueApp.core-1.0-SNAPSHOT.jar

**Comment by girishadobe** [comment]
I have updated the download links. This should work now
