### ISSUE TITLE
The link to - Downlaod and deploy the SetValue Custom OSGI Bundle - doesn't work

### ISSUE THREAD

**Issue by masumalli** [AdobeDocs/experience-manager-learn.en#55]
Issue in help/forms/handling-form-submissions/invoking-aem-workflow-on-form-submission-article-use.md

Downlaod and deploy the SetValue Custom OSGI Bundle
https://forms.enablementadobe.com/content/DemoServerBundles/SetValueApp.core-1.0-SNAPSHOT.jar

**Comment by girishadobe** [comment]
I have added the jar file. Can you please try and let me know if this is still not working
Thanks
