### ISSUE TITLE
Email service for sandbox env

### ISSUE THREAD

**Issue by bartoszWesolowski** [AdobeDocs/experience-manager-learn.en#57]
Issue in ./help/cloud-service/networking/examples/email-service.md

Hello,

This page describe how to configure the SMTP server with advanced networking - it does not show how to do it without this setting (for example for sandbox env). I think it would be useful to also provide some additional resources here describing how this can be configured. 

Cheers,
Bartek

**Comment by davidjgonzalez** [comment]
Hi @bartoszWesolowski - per the table at the top of Advanced Networking page, you can see that Sandboxes do not support  advanced networking, so you wont be able to test SMTP from there.

https://experienceleague.adobe.com/docs/experience-manager-learn/cloud-service/networking/advanced-networking.html
