### ISSUE TITLE
wknd-2.0.0 onwards the graphql proxy is not working anymore

### ISSUE THREAD

**Issue by nirmaljosehere** [AdobeDocs/experience-manager-learn.en#58]
Issue in ./help/headless-tutorial/graphql/quick-setup/local-sdk.md

At step 2.1, I went and downloaded https://github.com/adobe/aem-guides-wknd/releases/tag/aem-guides-wknd-2.0.0 as thats the latest. But that is broken and graphql call is returning an error. I tried with https://github.com/adobe/aem-guides-wknd/releases/tag/aem-guides-wknd-1.1.0 and this is working fine.

**Comment by nirmaljosehere** [comment]
Also, as per the screenshot for 3.6, the call is made to http://localhost:4502/content/graphql/global/endpoint.json. But for me, the call is actually to http://localhost:3000/content/graphql/global/endpoint.json

**Comment by davidjgonzalez** [comment]
Hi - the local AEM SDK tutorial should be updated to be compatible w/ WKND 2.0.0 now. 

The Cloud Service counterpart is being updated as we speak.
