### ISSUE TITLE
[AEM] Launch URI in AEM does not match the actual URI in Adobe Launch

### ISSUE THREAD

**Issue by jbrarAdobe** [AdobeDocs/experience-manager-learn.en#59]
Issue in help/sites/integration/adobe-launch-integration-tutorial-understand.md

Right above the Caution before the Additional Resource. We need to add the following:

You might run into an issue where Launch URI in AEM is not matching with the actual launch URI. In that case, please copy-paste the Launch library URI from Adobe Launch to AEM.

**Comment by godanny86** [comment]
A new video has been recorded that shows comparing the Launch URI in AEM with the URI in the Launch UI: https://docs.adobe.com/content/help/en/experience-manager-learn/sites/integrations/experience-platform-launch/create-launch-cloud-service.html
