### ISSUE TITLE
Assigning groups to prod profiles

### ISSUE THREAD

**Issue by sebastianedberg** [AdobeDocs/experience-manager-learn.en#6]
Issue in ./help/cloud-service/accessing/adobe-ims-product-profiles.md

Seems it is now possible to add groups to profiles so might be good to add about that

**Comment by godanny86** [comment]
ah @sebastianedberg good call out! Will make an update.

**Comment by davidjgonzalez** [comment]
The videos have been updated to include this new enhancement.
