### ISSUE TITLE
Setting up Integrated Dev Envrionment for Eclipse

### ISSUE THREAD

**Issue by dcuselton950** [AdobeDocs/experience-manager-learn.en#6]
Issue in help/getting-started-wknd-tutorial-develop/project-setup.md

The link for how to do this leads to a tutorial on how to install a new archtype project based upon importing a package like from Git.  It does not show how to find the project that has already been installed with the command line. When Is start eclipse, I have no idea how to get Eclipse to sync backwards from the CL induced project. Sorry my skills are remedial, but trying to learn.

**Comment by dcuselton950** [comment]
I was able to delete all old projects, and then use the chapter solutions download from Git Hub to then install chapter one and that got me into alignment. Is there no way to just access an existing project that we installed with command line and pull that back to Eclipse?

**Comment by godanny86** [comment]
> Is there no way to just access an existing project that we installed with command line and pull that back to Eclipse?

@dcuselton950 it is the same process as importing maven project that you created from the command line as it would be for importing that chapter solution. In the eclipse import wizard you just need to navigate to the location on the file system in which you created the project on the command line...

**Comment by dcuselton950** [comment]
Ok, so I have switched to doing the initial Archetype straight from eclipse. Still does not look like your your screen captures. For example, selecting the base page structure does not show JCR properties for that node.....standard issue Adobe Mac Laptop

![image](https://user-images.githubusercontent.com/19351790/59152740-607d4900-89ff-11e9-9a21-3859a0f9318d.png)

**Comment by godanny86** [comment]
you need to expand the Node representation (folder with the globe on it)

![image](https://user-images.githubusercontent.com/8974514/59152788-658ec800-8a00-11e9-8e69-268d5e042805.png)

**Comment by dcuselton950** [comment]
that must be part of my problem, I have not globe on mine and that folder has no content. hmmmmm

**Comment by godanny86** [comment]
Ah ok.
Right + Click the ui.apps project > **Properties**. Verify that the Content Sync directory points to `src/main/content/jcr_root`
![image](https://user-images.githubusercontent.com/8974514/59152859-96233180-8a01-11e9-8bf7-0350b54903e9.png)

See 05:40 in the AEM Development with Eclipse IDE video on https://helpx.adobe.com/experience-manager/kt/platform-repository/using/local-aem-dev-environment-article-setup.html

**Comment by dcuselton950** [comment]
Should have looked at that closer……video made it appear that it defaulted to that, but it did not. That is fixing it and I am also doing the same for UI.content

**Comment by dcuselton950** [comment]
thanks so much...

**Comment by dcuselton950** [comment]
resolved well
