### ISSUE TITLE
[AEM Assets] Mention aspect ratio dependency in Smart Crop documentation

### ISSUE THREAD

**Issue by deepa02** [AdobeDocs/experience-manager-learn.en#60]
Issue in help/assets/dynamic-media/smart-crop-feature-video-use.md

Smart Crop coordinates are aspect ratio dependent. i.e. for the various smart crop settings in image profile, if the aspect ratio is same for the added dimensions (in the image profile), then a same aspect ratio is sent to Dynamic media. Due to this , same crop area is suggested and there is no impact of different dimensions used in the profile.
This should be mentioned in the Smart Crop document.
**we want to mention in the doc that "the aspect ratio of the dimensions (added in the crop settings ) are being used to suggest smart crops. e.g. a crop settings for 100X100 and 200X200 would result in same smart crop being generated by the system".**

**Comment by godanny86** [comment]
fixed!
