### ISSUE TITLE
OAuth 1.0a & 2.0 Documentation link incorrect

### ISSUE THREAD

**Issue by chekurisriharsha** [AdobeDocs/experience-manager-learn.en#61]
Issue in ./help/foundation/authentication/authentication-support-article-understand.md

Can you please fix the link to OAuth 1.0a & 2.0 documentation on this page.

**Comment by davidjgonzalez** [comment]
I've updated the link to point to: https://experienceleague.adobe.com/docs/experience-manager-gems-events/assets/oauth-server-functionality-in-aem-7-23-14.pdf
