### ISSUE TITLE
[AEM] wild card for query parameters in SDI does not worked

### ISSUE THREAD

**Issue by ramchaa1** [AdobeDocs/experience-manager-learn.en#61]
How do i whitelist all query parameters for components? Isn't there a wild card '*' for query parameters , so that all my request for a component gets honored by AEM publisher instead of cached content.

**Comment by davidjgonzalez** [comment]
Sorry for the (very) tardy response - this should be covered in Dispatcher docs -- there is nothing special you need to do in the context of SDI, the SDI include will be treated by Dispatcher as "yet another" HTTP request.


https://experienceleague.adobe.com/docs/experience-manager-dispatcher/using/configuring/dispatcher-configuration.html?lang=en#enabling-access-to-vanity-urls-vanity-urls#restricting-query-strings
