### ISSUE TITLE
Step to Updating OSGI service "Apache sling authentication service" should be there on this page to avoid confusion. 

### ISSUE THREAD

**Issue by tnetake** [AdobeDocs/experience-manager-learn.en#62]
Issue in ./help/cloud-service/authentication/saml-2-0.md

When customer set path as /content/<customer-repository> in path property of com.adobe.granite.auth.saml.SamlAuthenticationHandler~saml.cfg.json OSGI configuration and when customer hit http://<host>:<IP>/content/<customer-repository> page isn't redirecting to IDP login page. Customer have to configure  OSGI service "Apache sling authentication service"  to add path /content/<customer-repository> in  property "sling.auth.requirements" . E.g for like this 

Create a file with the below PID

org.apache.sling.engine.impl.auth.SlingAuthenticator

{
  "auth.annonymous": true,
  "auth.http": "preemptive",
  "auth.http.realm": "Sling (Development)",
  "auth.sudo.cookie": "sling.sudo",
  "auth.sudo.parameter": "sudo",
  "sling.auth.requirements": [
    "+/libs/granite/oauth/content/authorization",
    "/content/<customer-repository>"
    ]
}
The above step of updating OSGI service "Apache sling authentication service" should be there on this page to avoid confusion. 

Thanks,
Tushar

**Comment by davidjgonzalez** [comment]
Hi!

Setting up authorization requirements is a subsequent concern - there are a lot of ways to do this - I prefer using CUGs over that osgi service tho, and would only recommend using that osgi as a backup when cugs/acls arent sufficient 

I wanted to make a supplemental guide Covering this topic, but ran out of time :(
