### ISSUE TITLE
Empty Bullet Points in Headless Tutorial

### ISSUE THREAD

**Issue by dpogni** [AdobeDocs/experience-manager-learn.en#62]
Issue in help/headless-tutorial/./chapter-2.md

Various bullet points in "Defining the structure of the Content Fragment Model" are empty on Adobe Docs page. 

See missing bullet points on this page:
https://docs.adobe.com/content/help/en/experience-manager-learn/getting-started-with-aem-headless/chapter-2.html

**Comment by dpogni** [comment]
There's also empty bullet points in this markdown file:
https://github.com/AdobeDocs/experience-manager-learn.en/blob/master/help/headless-tutorial/chapter-3.md

**Comment by godanny86** [comment]
Thanks @dpogni we are on it!

**Comment by godanny86** [comment]
This has been resolved:
https://docs.adobe.com/content/help/en/experience-manager-learn/getting-started-with-aem-headless/chapter-3.html
https://docs.adobe.com/content/help/en/experience-manager-learn/getting-started-with-aem-headless/chapter-2.html
