### ISSUE TITLE
InDesign server - download link

### ISSUE THREAD

**Issue by bartoszWesolowski** [AdobeDocs/experience-manager-learn.en#64]
Issue in ./help/assets/asset-templates/asset-templates-technical-video-setup.md

Hello,

Is this documentation up to date? It seems that setting up/downloading InDesign Server has changed. I could not find InDesign Server installation files using provided links / included video. I can only see this download options when I follow the documentation 
<img width="786" alt="image" src="https://user-images.githubusercontent.com/9348327/178449640-5dfe1847-8fe1-4969-8691-007fa5c63d72.png">

Any help would be great here :) 
Thanks!

**Comment by davidjgonzalez** [comment]
I believe it now available via: https://www.adobeprerelease.com/

Ill update the link on the docs as well!
