### ISSUE TITLE
[AEM Assets] Improper sentence structure and "secs" is not a word

### ISSUE THREAD

**Issue by johnb4** [AdobeDocs/experience-manager-learn.en#65]
Issue in help/assets/./creative-workflows/adobe-asset-link.md

1. "secs" is not a word. It's "seconds".
2. This sentence fragment needs work "the original full-resolution asset gets replaces the lower resolution image and it all happens in the background." The words "gets replaces" should probably be "gets replaced". And what what does "it all happens in the background" supposed to mean? It's not automatic. It should probably "The lower resolution image is placed temporarily and when the final output is required for printing or publishing, you need to replace the FPO renditions with the originals. If you want to replace multiple FPO images with respective original images, choose the **Download all Originals** option. After the original images are downloaded, choose **Replace all FPOs With Originals**.

**Comment by godanny86** [comment]
fixed!
