### ISSUE TITLE
[AEM Assets] Missing Video Content on Adobe Asset Link - Place Link

### ISSUE THREAD

**Issue by rockstarlearner** [AdobeDocs/experience-manager-learn.en#67]
Issue in help/assets/./adobe-asset-link/place-linked.md

Link : https://docs.adobe.com/content/help/en/experience-manager-learn/assets/adobe-asset-link/place-linked.html

Missing video link

![image](https://user-images.githubusercontent.com/64078030/86990247-cc5d5280-c1b9-11ea-8962-3a65546f2c13.png)
:

**Comment by davidjgonzalez** [comment]
Thanks @rockstarlearner - we'll get on this right away!

**Comment by godanny86** [comment]
fixed!
