### ISSUE TITLE
[AEM Sites] Outdated UIs for Adobe I/O and Adobe Launch

### ISSUE THREAD

**Issue by johnb4** [AdobeDocs/experience-manager-learn.en#68]
Issue in help/sites/integration/adobe-launch-integration-tutorial-understand.md

In "Step 2: Connect Adobe IO and Adobe Experience Manager" there is a video which shows how to use console.adobe.io.
It's out of date and needs to be recreated. The current version of console.adobe.io has a completely new UI and it's not clear to our customers how to navigate it; especially to those customers who have never used it.
If a website navigation's is revamped, it's supporting documentation needs be also.
[Same problem with https://helpx.adobe.com/experience-manager/using/aem_launch_adobeio_integration.html]

**Comment by godanny86** [comment]
Hey @johnb4 totally agree. We are actually in the middle of refreshing those videos.

**Comment by godanny86** [comment]
The Adobe Launch UI has also changed significantly which would necessitate re-recording. Since the AEM UI has also changed somewhat and the reference site is We.Retail (instead of WKND) we will recreate the entire video series.

**Comment by godanny86** [comment]
A new set of videos have been published: https://docs.adobe.com/content/help/en/experience-manager-learn/sites/integrations/experience-platform-launch/overview.html. Redirects from old content will put in place next week.
