### ISSUE TITLE
Formatting Broken

### ISSUE THREAD

**Issue by blentz100** [AdobeDocs/experience-manager-learn.en#68]
With sections:

4 - Client-Side Libraries
5 - Style System
6 - Custom Component

the formatting appears off. The right hand column is gone and the main text of the page is running of the edge with no way to scroll right to see the rest of it. I've tried multiple browsers.
<img width="1183" alt="Screen Shot 2022-07-19 at 3 52 57 PM" src="https://user-images.githubusercontent.com/66037960/179861764-f3b15de8-bb24-49c1-8643-c0828f0e422d.png">

**Comment by davidjgonzalez** [comment]
This has been fixed in a CSS updated deployed to ExL.
