### ISSUE TITLE
[AEM] Where at Adobe is the documentation for "Configuration Browser"?

### ISSUE THREAD

**Issue by johnb4** [AdobeDocs/experience-manager-learn.en#69]
Issue in help/sites/personalization/context-hub-technical-video-setup.md

There is a mention of it on the this page (one single sentence).
But, where at Adobe is the documentation for "Configuration Browser"? I cannot find it. 
A google search of [aem "Configuration Browser"] leads to only one result at *.adobe.com >> https://docs.adobe.com/content/help/en/experience-manager-learn/getting-started-with-aem-headless/chapter-2.html 
and that does not define, just mentions it when discussing the creation of Content Fragments.

What is it's purpose? How is it used? What does it affect? If it's not defined, what does not work?
Where is it defined in the JCR?

If customers are defining their own sites (and related items like Context Hubs, Segments, Templates, etc), this needs to be created, so where is the documentation that state this explicitly and defines it's purpose?

**Comment by davidjgonzalez** [comment]
@bohnertchris any idea if this exists in Adobe AEM product documentation?

**Comment by bohnertchris** [comment]
AEM configurations can be thought of as workspaces used to manage settings in AEM, activate certain features, and manage access.

Details are found in the Configuration Browser documentation.

https://docs.adobe.com/content/help/en/experience-manager-cloud-service/implementing/developing/configurations.html
https://docs.adobe.com/content/help/en/experience-manager-65/administering/introduction/configurations.html
https://docs.adobe.com/content/help/en/experience-manager-64/administering/introduction/configurations.html

**Comment by godanny86** [comment]
Thanks @bohnertchris !
