### ISSUE TITLE
asset location in apps

### ISSUE THREAD

**Issue by steve-farwell** [AdobeDocs/experience-manager-learn.en#70]
Issue in help/sites/developing/style-system-technical-video-understand.md

the content in the zip filehttps://docs.adobe.com/content/help/en/experience-manager-learn/sites/developing/assets/technical-review.sites.style-system-1.0.0.zip ,   adds the clientlib in apps/demo not apps/enablement

**Comment by davidjgonzalez** [comment]
Thanks @steve-farwell

**Comment by godanny86** [comment]
fixed!
