### ISSUE TITLE
Broken Link - Missing content - Fluid Personalization video

### ISSUE THREAD

**Issue by paran-k** [AdobeDocs/experience-manager-learn.en#71]
Issue in help/sites/personalization/experience-fragment-target-offer-feature-video-use.md

Under "Additional Resources" at the bottom of the page the "Fluid personalisation" video links to a locked/removed video. Can you please update and/or send me a link to the correct video? A client is asking for it. Thanks!

Additional Resources > Fluid Personalization - AEM Experience Fragments in Adobe Target:
Broken/wrong link: https://www.youtube.com/watch?v=ohvKDjCb1yM
![Screenshot 2020-07-22 at 10 05 06](https://user-images.githubusercontent.com/68638891/88157571-d85a0300-cc02-11ea-9b22-2209b40db80b.png)

https://docs.adobe.com/content/help/en/experience-manager-learn/sites/personalization/experience-fragment-target-offer-feature-video-use.html

**Comment by godanny86** [comment]
this has been fixed.
