### ISSUE TITLE
First mvn command inaccuracy

### ISSUE THREAD

**Issue by muellerpeter8** [AdobeDocs/experience-manager-learn.en#73]
Issue in ./help/headless-tutorial/spa-editor/react/create-project.md
The very first mvn command in the tutorial that sets up the project file structure creates different files than what is shown and subsequently causes errors in the mvn build. Thus starting the tutorial is not possible.

**Comment by davidjgonzalez** [comment]
@muellerpeter8 i went through and updated the structure for Archetype 39, so this should be resolved when published. Do you recall if there was anything specific that was causing you trouble (want to make sure i didnt miss it). THanks
