### ISSUE TITLE
single-sign-on-with-okta page should be sanitized

### ISSUE THREAD

**Issue by thedoc31** [AdobeDocs/experience-manager-learn.en#75]
Issue in help/forms/adaptive-forms/single-sign-on-with-okta.md

The screenshots in this article contain a number of items which should be obfuscated or removed entirely. For instance, the "AEM Trials" form is from our internal SSO portal. The third screenshot of the SAML Authentication Handler config contains sensitive information which should not be revealed to the public. Similarly, the Sling Referer filter screenshot "allow hosts" should not be revealed to the public. 

Also suggest adding a link to the official Okta doc [1] which could help.

[1]
https://saml-doc.okta.com/SAML_Docs/How-to-Configure-SAML-for-Adobe-CQ.html

**Comment by godanny86** [comment]
This has been fixed. Thanks @thedoc31 !
