### ISSUE TITLE
Advanced networking - Email service missing link to legacy setup

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/experience-manager-learn.en#75]
Issue in ./help/cloud-service/networking/examples/email-service.md

Somewhere in here, there needs to be a link to https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/implementing/developing/development-guidelines.html?lang=en#legacy-email-configuration which talks about the requirements. Ie. only certain ports are allowed.

**Comment by davidjgonzalez** [comment]
I added a link to the page, however it seems like this only pertains to now very old (legacy) deployments that didnt use advanced networking? It says these considerations are only valid for people setting this up prior to 2021.9 which is ~ a year ago -- do you know if this actually affects anyone today?

**Comment by alisonasanchez** [comment]
I'm not sure if the port requirements are for only legacy or all egress IP's. Can we find out and document that? I tend to think that if it is a requirement for legacy systems, it is probably also a requirement for current versions as well. But, it's not documented anywhere that I can find, so.... here we are.
