### ISSUE TITLE
Video tutorials are not ordered in the correct sequence

### ISSUE THREAD

**Issue by fGhazala** [AdobeDocs/experience-manager-learn.en#78]
There is an ordering problem in the listed videos on this page. The first and Second Video is the same and last tutorial is missing. Undeniably, the content is very helpful. Issue in help/sites/integration/adobe-launch-integration-tutorial-understand.md

**Comment by godanny86** [comment]
hi @fGhazala we actually are in the process of redirecting users to a newly recorded video series: https://docs.adobe.com/content/help/en/experience-manager-learn/sites/integrations/experience-platform-launch/overview.html. It is the same content but recorded with latest UIs.
