### ISSUE TITLE
[AEM Assets] This tutorial assumes a few things from the start that may not be true

### ISSUE THREAD

**Issue by duselton** [AdobeDocs/experience-manager-learn.en#79]
Issue in help/assets/configuring/baseline-folders.md

This assumes that someone has installed the WKND sites tutorial and the Dropbox folders extension. Baseline quickstart jar does not have those things. 

Maybe either set the prerequisites as part of the tutorial or work based on the default right now of We.Retail

**Comment by davidjgonzalez** [comment]
@duselton  how are you accessing this content? It's not really a tutorial - it explains core concepts.
Also, Drop box is just an example name of a folder its not "Dropbox" TM not is there any special extension/integration.
