### ISSUE TITLE
node-sass NPM package sometimes breaks mvn build

### ISSUE THREAD

**Issue by sgeier** [AdobeDocs/experience-manager-learn.en#82]
Issue in https://docs.adobe.com/content/help/en/experience-manager-learn/spa-react-tutorial/create-project.html concerning step 3.

Depending on the OS of the user the node-sass configuration can fail during mvn builds.

**Error:** Missing binding AEM_React_Workshop/Selfrun/aem-guides-wknd-spa/ui.frontend/node_modules/node-sass/vendor/darwin-x64-72/binding.node
Node Sass could not find a binding for your current environment: OS X 64-bit with Node.js 12.x

A solution is to rebuild the node-sass cache during build time by adding another execution step in the pom.xml of ui.frontend before the actual npm run build execution step.

See the block below:

`<execution>
  <id>npm rebuild node-sass</id>
          <goals>
                            <goal>npm</goal>
                        </goals>
                        <configuration>
                            <arguments>rebuild node-sass</arguments>
                        </configuration>
                    </execution>
                    <execution>`

**Comment by godanny86** [comment]
Thanks @sgeier! We try to keep the project aligned with the AEM Project Archetype. I'll create an issue in that repo.
