### ISSUE TITLE
[AEM Assets] missing information about how to set up Asset Compute Worker using aio cli without logging in

### ISSUE THREAD

**Issue by jdelbick** [AdobeDocs/experience-manager-learn.en#83]
Issue in ./help/cloud-service/asset-compute/develop/project.md
[Generating a project](https://github.com/AdobeDocs/experience-manager-learn.en/blob/master/help/cloud-service/asset-compute/develop/project.md#generate-a-project) #2 says:

> If you are unable to log in, please follow these instructions on how to generate a project.

is it just missing the link (or is this content just missing) regarding how to set up a project (and attach the credentials) without logging in? here are the firefly instructions for trouble logging in through the cli: https://github.com/AdobeDocs/project-firefly/blob/master/getting_started/first_app.md#42-developer-is-not-logged-in-as-enterprise-organization-user

**Comment by jdelbick** [comment]
@davidjgonzalez

**Comment by davidjgonzalez** [comment]
Thanks, @jdelbick  - yes, that is what I meant! I'll update the link - thank you for calling it out!
