### ISSUE TITLE
Client question on file create-project.md

### ISSUE THREAD

**Issue by yanlicao** [AdobeDocs/experience-manager-learn.en#84]
Dear team
We received this comment at https://github.com/AdobeDocs/experience-manager-learn.pt-BR/issues/1
Issue in ./help/headless-tutorial/spa-editor/react/create-project.md
I followed step by step the documentation on how to start a react spa project but I couldn't see or use the default Text component and when checking the templates I see that the one used as default does not contains the component, I tried to use the Remote SPA Page template, that contains the Text component, but got a blank page and also no components to use. Is there any useful tutorial on how to implement React or Angular in AEM?
Can you please advise? 
Please also feel free to reply directly in the pt-BR issue if that is more convenient for you."

**Comment by yanlicao** [comment]
Dear team, can you reply this question please? 
As client is waiting.

**Comment by davidjgonzalez** [comment]
Can you try out whats outlined in: 

https://github.com/AdobeDocs/experience-manager-learn.en/issues/85#issuecomment-1282568444
