### ISSUE TITLE
[AEM Assets] Issue in help/assets/dynamic-media/dynamic-media-interactive-video-feature-video-use.md | Associated products are visible outside the duration of last segment

### ISSUE THREAD

**Issue by pooja-chauhan** [AdobeDocs/experience-manager-learn.en#85]
Associated products  should not be  visible outside the duration of last segment.

**Comment by davidjgonzalez** [comment]
@pooja-chauhan  - This sounds like a product issues/enhancement more than something with the video content (as the video shows the feature as it works). Please re-open this issue if ive misunderstood. Also, please feel free to log Adobe Support Tickets for issues or enhancements you might notice.
