### ISSUE TITLE
[AEM Forms] How to externalize API key for Geolocation API

### ISSUE THREAD

**Issue by pawee-del** [AdobeDocs/experience-manager-learn.en#86]
Issue in help/forms/adaptive-forms/using-geolocation-api-in-aem-forms-article.md

the article doesn't say how to externalise the api key, i am more looking to use configuration container rather than osgi, is there a way to do that?

**Comment by girishadobe** [comment]
are you concerned about the API key being visible in the code? If so we get create a Form Data Model if there are REST API for geolocation.

**Comment by davidjgonzalez** [comment]
@pawee-del It appears this has been answered. Please re-open if you require more clarification. thanks!
