### ISSUE TITLE
Wrong step

### ISSUE THREAD

**Issue by flashravi** [AdobeDocs/experience-manager-learn.en#89]
Issue in help/cloud-service/./local-development-environment/development-tools.md

Set up the Adobe I/O CLI Asset Compute plugin
The Adobe I/O Cloud Manager plugin allows the aio CLI to generate and run Asset Compute workers via the aio asset-compute command.
Execute aio plugins:install @adobe/aio-cli-plugin-cloudmanager to install the aio Asset Compute plug-in .

*******The above command is suppose to be 

Execute aio plugins:install @adobe/aio-cli-plugin-asset-compute to install the aio Asset Compute plug-in .

**Comment by davidjgonzalez** [comment]
Thanks! This should be fixed now!
