### ISSUE TITLE
Package included in tutorial does not have three template options, only one

### ISSUE THREAD

**Issue by kr1st1nagr03g3r** [AdobeDocs/experience-manager-learn.en#9]
Issue in ./help/forms/creating-your-first-adaptive-form/create-adaptive-form-template.md

When download the [package in the article](https://experienceleague.adobe.com/docs/experience-manager-65/forms/adaptive-forms-advanced-authoring/template-editor.html?lang=en): 

It only downloads one option, when there are three in this video tutorial.

![image](https://user-images.githubusercontent.com/94015887/149372912-9c79cb3c-f829-4f37-99d5-897dd6eafb6f.png)

**Comment by girishadobe** [comment]
Thanks for the feedback.
the template that is created in this tutorial is included in the package. The other two templates come with the product..

**Comment by girishadobe** [comment]
The sample template is included in the package. The other two templates come with the OOTB AEM Forms installation
