### ISSUE TITLE
Wrong Command

### ISSUE THREAD

**Issue by jaijyothis** [AdobeDocs/experience-manager-learn.en#9]
Issue in help/getting-started-wknd-tutorial-develop/project-setup.md

https://docs.adobe.com/content/help/en/experience-manager-learn/getting-started-wknd-tutorial-develop/project-setup.html has the following command which failed.

 mvn archetype:generate \
  -DarchetypeGroupId=com.adobe.granite.archetypes \
  -DarchetypeArtifactId=aem-project-archetype \
  -DarchetypeVersion=18

The following command worked. I got the command from 
https://github.com/adobe/aem-project-archetype/issues/142

mvn org.apache.maven.plugins:maven-archetype-plugin:2.4:generate \ 
-DarchetypeGroupId=com.adobe.granite.archetypes \ 
-DarchetypeArtifactId=aem-project-archetype \ 
-DarchetypeVersion=18\ 
-DarchetypeCatalog=https://repo.adobe.com/nexus/content/groups/public

Please update the command or give this as an additional information

**Comment by godanny86** [comment]
hi @jaijyothis thank you for raising! The command in the tutorial is a reflection of the usage instructions on the AEM Project archetype readme: https://github.com/adobe/aem-project-archetype#usage

Just to verify you have:
* Apache Maven (3.3.9 or newer)
* Added the Adobe Public Maven Repository in Maven settings (first couple of steps in the project-setup page

What is the error you get when executing:

```shell
 mvn archetype:generate \
  -DarchetypeGroupId=com.adobe.granite.archetypes \
  -DarchetypeArtifactId=aem-project-archetype \
  -DarchetypeVersion=18
```

**Comment by jaijyothis** [comment]
C:\Users\SDSA>mvn archetype:generate
-DarchetypeGroupId=com.adobe.granite.archetypes
-DarchetypeArtifactId=aem-project-archetype  -DarchetypeVersion=18
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------< org.apache.maven:standalone-pom
>-------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] --------------------------------[ pom
]---------------------------------
[INFO]
[INFO] >>> maven-archetype-plugin:3.1.1:generate (default-cli) >
generate-sources @ standalone-pom >>>
[INFO]
[INFO] <<< maven-archetype-plugin:3.1.1:generate (default-cli) <
generate-sources @ standalone-pom <<<
[INFO]
[INFO]
[INFO] --- maven-archetype-plugin:3.1.1:generate (default-cli) @
standalone-pom ---
[INFO] Generating project in Interactive mode
[WARNING] Archetype not found in any catalog. Falling back to central
repository.
[WARNING] Add a repository with id 'archetype' in your settings.xml if
archetype's repository is elsewhere.
[WARNING] The POM for
com.adobe.granite.archetypes:aem-project-archetype:jar:18 is missing, no
dependency information available
[INFO]
------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO]
------------------------------------------------------------------------
[INFO] Total time:  11.157 s
[INFO] Finished at: 2019-07-12T16:41:22-04:00
[INFO]
------------------------------------------------------------------------
[ERROR] Failed to execute goal
org.apache.maven.plugins:maven-archetype-plugin:3.1.1:generate
(default-cli) on project standalone-pom: The desired archetype does not
exist (com.adobe.granite.archetypes:aem-project-archetype:18) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e
switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions,
please read the following articles:
[ERROR] [Help 1]
http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by godanny86** [comment]
hi @jaijyothis thanks for sending the error. And you get this error even after adding the Adobe nexus repo to your .m2/settings.xml ?

**Comment by godanny86** [comment]
@jaijyothis please see the revisions to: https://docs.adobe.com/content/help/en/experience-manager-learn/getting-started-wknd-tutorial-develop/project-setup.html. Feel free to re-open if you have more details.

**Comment by jaijyothis** [comment]
HI Daniel,

Used this command to resolve the issue => mvn archetype:generate -DarchetypeGroupId=com.adobe.granite.archetypes -DarchetypeArtifactId=aem-project-archetype -DarchetypeVersion=19 -Padobe-public                                                                                                                   
Also used the command => mvn -PautoInstallPackage -Padobe-public clean install             
 
added <useProxy>false</useProxy> in pom.xml

            <plugin>
                    <groupId>com.day.jcr.vault</groupId>
                    <artifactId>content-package-maven-plugin</artifactId>
                    <version>1.0.2</version>
                    <configuration>
                        <targetURL>http://${aem.host}:${aem.port}/crx/packmgr/service.jsp</targetURL>
                        <failOnError>true</failOnError>
                        <userId>${vault.user}</userId>
                        <password>${vault.password}</password>
                        <useProxy>false</useProxy>
                    </configuration>
                </plugin>

Regards,
Jaison
