### ISSUE TITLE
[AEM Sites] Use text for warning message along with image

### ISSUE THREAD

**Issue by knennigtri** [AdobeDocs/experience-manager-learn.en#90]
Issue in help/sites/integrations/adobe-target/load-and-fire-target.md

I was having the issue of the mboxDisable cookie wasn't set: https://docs.adobe.com/content/help/en/experience-manager-learn/sites/integrations/target/load-and-fire-target.html#common-issues

I've been googling the message everywhere and only by chance did I stumble on this page. I think if the error message was text, it would be more searchable and this article would be found when developers run into this.

``` console
> AT: [page-init] Adobe Target content delivery is disabled. Ensure that you can save cookies to your current domain, there is no "mboxDisable" cookie and there is no "mboxDisable" parameter in the query string.
```

**Comment by davidjgonzalez** [comment]
great idea! thankS!
