### ISSUE TITLE
Documentation extension

### ISSUE THREAD

**Issue by bartoszWesolowski** [AdobeDocs/experience-manager-learn.en#94]
Issue in ./help/headless-tutorial/graphql/advanced-graphql/graphql-persisted-queries.md

Hello,

I am learning about AEM Headless and I started with video series and documentation form https://experienceleague.adobe.com/docs/experience-manager-learn/getting-started-with-aem-headless/overview.html?lang=en

I see that documentation about persisted queries is focused on the API that provides that feature but not on the AEM console where this could be set up manually - this got me the wrong impression persisted queries should be managed via API and there is no place to manage them centrally in the AEM. 

Thanks to the community forum I found that there is a UI for that and documentation can be found under AEM as Cloud Service documentation (https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/headless/graphql-api/graphiql-ide.html?lang=en)

Is this UI for managing persistent queries only available for AEM as a Cloud Service? I would be helpful to link to the other documentation and add some section that would explain what are the options for on prem and cloud set ups (if there is a difference).

Cheers, 
Bartek :)

**Comment by SachinMali** [comment]
@bartoszWesolowski  That's correct, as of now 'GraphiQL IDE' is built into the AEM as a Cloud Service. And for 6.x.x you can install it via package, we have steps outlined steps here at **Basic Tutorial** (https://experienceleague.adobe.com/docs/experience-manager-learn/getting-started-with-aem-headless/graphql/multi-step/explore-graphql-api.html?lang=en#install-graphiql)

However, [Advanced Tutorial](https://experienceleague.adobe.com/docs/experience-manager-learn/getting-started-with-aem-headless/graphql/multi-step/overview.html?lang=en#advanced-tutorial) is lagging behind the updates and will be prioritized soon.

Appreciated your patience.

**Comment by SachinMali** [comment]
This has been addressed by editing the

[Advanced Concepts of AEM Headless](https://experienceleague.adobe.com/docs/experience-manager-learn/getting-started-with-aem-headless/graphql/advanced-tutorial/overview.html?lang=en)

**Caution Note on Videos**

[Creating GraphQL Queries](https://experienceleague.adobe.com/docs/experience-manager-learn/getting-started-with-aem-headless/graphql/video-series/creating-graphql-queries.html?lang=en)

[GraphQL Persisted Queries](https://experienceleague.adobe.com/docs/experience-manager-learn/getting-started-with-aem-headless/graphql/video-series/graphql-persisted-queries.html?lang=en)

Please
