### ISSUE TITLE
Changes in react app not deployed

### ISSUE THREAD

**Issue by bartoszWesolowski** [AdobeDocs/experience-manager-learn.en#96]
Issue in ./help/headless-tutorial/spa-editor/react/map-components.md

Hello, 

I created the project using the lates archetype for AEM 6.5.9 with this maven command:
```
 mvn -B archetype:generate  -D archetypeGroupId=com.adobe.aem  \
    -D archetypeArtifactId=aem-project-archetype \
    -D archetypeVersion=39  \
    -D appTitle="WKND SPA React"  \
    -D appId="wknd-spa-react"  \
    -D artifactId="aem-guides-wknd-spa.react" \
    -D groupId="com.adobe.aem.guides.wkndspa.react"  \
    -D frontendModule="react"  \
    -D aemVersion="6.5.9"

```

When I followed the tutorial I noticed that deploying the app with `mvn clean install -PautoInstallSinglePackage` from the root directory does not deploy changes in the react app.

Steps to reproduce:
1. Change some component in `ui.frontend` module
2. Deploy changes using `mvn clean install -PautoInstallSinglePackage` from the root project level

Expected:
Changes in the model are visible on AEM instance.

Actual:
No changes visible.

Right now the only way I was able to deploy changes in the react app:
1. Run `npm run build` in `ui.frontend` module
2. Run `mvn clean install -PautoInstallPackage` in `ui.apps` module

I am not sure whether this bug should be created here or in the archetype repo :)

Cheers,
Bartek

**Comment by SachinMali** [comment]
Hello Bartek,

Can you please try upgrading the instance to 6.5.13 or 14 (service pack 13 or 14).. I think you are using latest archetype (39) but a bit older aem instance.

Thanks
Sachin
