### ISSUE TITLE
[AEM CS] Conflicting information around IMS User Groups/Product Profile support

### ISSUE THREAD

**Issue by RyanADBE** [AdobeDocs/experience-manager-learn.en#97]
Issue in ./help/cloud-service/accessing/adobe-ims-product-profiles.md

I don't know if this is the correct way to raise this but there seems to be conflicting information on this page vs https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/security/ims-support.html?lang=en. 

This page suggests that IMS User Groups can be used in conjunction with AEM groups, and that functionality will be passed between them whereas the page noted above states that IMS user groups should NOT be used with AEM as a Cloud Service as they don't work.

**Comment by davidjgonzalez** [comment]
@RyanADBE im not seeing where the conflict is here. Can you point out exactly where you're seeing the contradictory guidance? The Video itself focuses more on the Product Profiles as well, rather than user groups.

**Comment by RyanADBE** [comment]
Hi @davidjgonzalez, thanks for your message. If you go to 2.53 in the video onwards, IMS user groups are given as an option for use with AEMaaCS but the other page suggests we shouldn't do this.

**Comment by davidjgonzalez** [comment]
Not sure I'm follow .. the video says you can add groups to product profiles (or users) and rhe docs say: Any users and groups added under this product profile will be able to login to that particular instance as shown in the example below:...

So it too is saying you can add groups (or users) to PP.

**Comment by RyanADBE** [comment]
It's just this line that seems to suggest that we shouldn't be using User Groups: "AEM currently does not support assigning groups to profiles. Users should be added individually instead."

**Comment by RyanADBE** [comment]
Hi @davidjgonzalez, I'm wondering if the root of this recommendation to not use User Groups was due to this bug: https://jira.corp.adobe.com/browse/IDOPS-7328

**Comment by davidjgonzalez** [comment]
@RyanADBE ahh - gotcha. Somehow my brain never reads those notes :(  

Im replacing this issue, with a new one for the Documentation page as AFIAK the video is correct (and Docs page is incorrect): https://github.com/AdobeDocs/experience-manager-cloud-service.en/issues/36
