### ISSUE TITLE
[AEM Foundation] Add CORS configuration regexp examples

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/experience-manager-learn.en#99]
Issue in ./help/foundation/security/understand-cross-origin-resource-sharing.md
I would like to get an example of what the alloworiginregexp value would look like. Can you please provide one in one of the examples? Like maybe for the more complicated one, allow *.site1.com and what that would look like.

**Comment by alisonasanchez** [comment]
Also, would be helpful in the examples to provide multiple values for alloworiginregexp and alloworigin so that we can see how those should be formatted.

**Comment by SachinMali** [comment]
@alisonasanchez For now can you please see https://github.com/adobe/aem-guides-wknd/blob/a51868804458b79427727c0320763b1112638b6b/ui.config/src/main/content/jcr_root/apps/wknd/osgiconfig/config.author/com.adobe.granite.cors.impl.CORSPolicyImpl~wknd-graphql.cfg.json

Hope this provides some insight.
